### ISSUE TITLE
Memory leak when batch converting images to HDR

### ISSUE THREAD

**Issue by alexeykv** [LuminanceHDR/LuminanceHDR#10]
Luminance leaks memory when running batch HDR.
It is stable reproducible on Windows and 2.4.0 version
Steps to reproduce:
Run HDR batch converter, select exr format, auto_align_images, autocrop. Run batch. With about 40 input images it leaks about 12G of memory

![hdr](https://cloud.githubusercontent.com/assets/1814126/9351577/65eb736e-4663-11e5-8dbe-fb8d2191570f.png)

**Comment by fcomida** [comment]
@alexeykv This has been fixed in 2.5.1. If not please open it again.
