### ISSUE TITLE
Macintosh build does not allow 10.11

### ISSUE THREAD

**Issue by mkarliner** [LuminanceHDR/LuminanceHDR#102]
I'm running El Capitan and a download of 2.5.1 tells me it is only for 10.12 and above.

**Comment by clanmills** [comment]
I think that was dealt with last year and 2.5.3 runs on El Cap.  I believe @HIREM will remember.

**Comment by Benitoite** [comment]
Greetings and sorry for the delay. @clanmills you misspelled my GitHub handle @benitoite


@mkarliner Yes we did make several mac changes in preparation for the upcoming release.

This is the development snapshot I've been testing on both 10.11 and 10.12. 
https://filebin.net/fu841fry89ozve0b/Luminance_HDR_2.5.2-SNAPSHOT-Test1h.dmg

This is a [testing fork](https://github.com/Benitoite/LuminanceHDR) build which includes many speedups not yet [pulled](https://github.com/LuminanceHDR/LuminanceHDR/pull/100) into [the official repo](https://github.com/LuminanceHDR/LuminanceHDR).

**Comment by fcomida** [comment]
@mkarliner @clanmills @Benitoite I'm closing this one.
