### ISSUE TITLE
Save As repopulates "files of type" combo without clearing it

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#111]
Once you have tone-mapped a HDR, click "Save as", cancel, click "Save as" again.
Every time you do this, the list of items in the combobox grows because its not cleared.
![screenshot_20180404_231711](https://user-images.githubusercontent.com/5844619/38336111-f8f31d5a-3860-11e8-96ee-03d0f07e678b.png)

**Comment by heckflosse** [comment]
I will take this. At least I will try...

**Comment by Beep6581** [comment]
@heckflosse look in https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/MainWindow/MainWindow.cpp#L112

**Comment by heckflosse** [comment]
Damn, pushed to wrong branch...
