### ISSUE TITLE
Batch Converting of EXR to TIFF(16bit)

### ISSUE THREAD

**Issue by urs-viktor-marti** [LuminanceHDR/LuminanceHDR#12]
Hi,

I have tried to convert a batch of EXR files with a defined tone mapping profile and save the images in a second location in TIFF (16bit) format. I observed the following behaviour:
- using version 2.4.0, the saving is not possible and an error is output in the protocol of the batch
- using version 2.3.1, the converted image is saved but only in 8 bit (using the properties -> detail option when right clicking onto the image output by LuminanceHDR)

**Comment by fcomida** [comment]
I just fixed it, thank you for reporting it.

**Comment by urs-viktor-marti** [comment]
I have tried to compile the source code, but I didn't succeed because the script considered conflicts in libpng versions, but also in CMake configurations (using MSVC10). Is there a possibility to get a fixed win64 (or win32) version to be downloaded as a daily build?

**Comment by fcomida** [comment]
Can you please post the error messages you got? Difficult to fix otherwise.
