### ISSUE TITLE
Different render outcome for same input

### ISSUE THREAD

**Issue by SaturnusDJ** [LuminanceHDR/LuminanceHDR#121]
I am still on 2.4 because 5.5-branch gives me extend noise and artifacts in Fattal operator.

For 2.4, I am already noticing for more than a year that let's say when doing a Fattal render (butother operators have this behaviour too) for 10 times. 5/10 would be a same good stable result. 3/10 would be different e.g. more saturated and the final 2/10 would be really messed up with RGB noise in light areas. What I do notice is that the histogram is moved more to the left or to the right.

Anyone else who experienced this?

(https://discuss.pixls.us/t/different-render-outcome-for-same-input/8602)

**Comment by heckflosse** [comment]
As you confirmed that it's fixed in 2.5.2.5f582a I close this issue.
