### ISSUE TITLE
Portable mode doesn't work

### ISSUE THREAD

**Issue by AlvaroHermida** [LuminanceHDR/LuminanceHDR#123]
Portable mode (Luminance-HDR-x64-SETUP-v2.5.1) fails on every run, issuing an out of memory message (although there is plenty of free memory and disk space).

![captura de pantalla 2018-08-23 12 55 37](https://user-images.githubusercontent.com/6568828/44521866-efb9aa00-a6d4-11e8-800f-9c92305d1cb5.png)

The non-portable mode doesn't fail in this way.

**Comment by fcomida** [comment]
I don't have access to any Windows machine right now so I installed LHDR 2.5.1 via wine on a linux machine in portable mode and it works. The database and settings.ini have been created in the same folder as the executable, no errors running and closing the program multiple times.

**Comment by AlvaroHermida** [comment]
I installed it on another REAL Windows 10 machine, and the portable mode fails issuing the same messages.
First it ask for money (no matter which button you press, it ALWAYS repeats the same panel):
![captura de pantalla 2018-08-30 14 48 28](https://user-images.githubusercontent.com/6568828/44852576-e1830500-ac63-11e8-8df9-663f98550f59.png)
Then, the out of memory message:
![captura de pantalla 2018-08-30 14 50 30](https://user-images.githubusercontent.com/6568828/44852776-6837e200-ac64-11e8-80f0-5541893d5a18.png)
and finally the app starts, but all the configuration changes are lost.

There is no settings.ini in the same folder as the .exe, but instead there is an empty "PortableMode.txt" file.  Manually adding the settings.ini file doesn't help.

**Comment by fcomida** [comment]
Is the filesystem writable by you? Are you able to run it on a different Windows for testing?
Again, I copied the "Luminance HDR" folder on a pendrive, deleted `saved_parameters.db` and `settings.ini` (which is created if you click on "No, ¡No me molestes mas!" button, and that explains why LHDR keeps asking you) from there and ran LHDR via wine (Windows 10 version) and it works.

**Comment by fcomida** [comment]
So yes, it's a file permissions issue, LHDR is not allowed to write into the filesystem and cannot create `saved_parameters.db` and `settings.ini`. I tested it removing read permission bits from `saved_parameters.db` and when I run LHDR I get the same error:
 
![screenshot_20180830_163912](https://user-images.githubusercontent.com/11018726/44858892-4c880800-ac73-11e8-9016-99f5cbe4be0d.png)

**Comment by clanmills** [comment]
Good find, @fcomida  I've downloaded the .exe and haven't fired up Windows yet as I've been busy in the garden today.  I won't do anything further about this.

**Comment by fcomida** [comment]
@clanmills @AlvaroHermida A new security feature of Windows 10? I doubt the filesystem is read-only or anything. Out of curiosity I googled a bit [Windows 10 - Cannot create file anywhere on drive C:](https://superuser.com/questions/1062725/cannot-create-file-anywhere-on-drive-c)

**Comment by clanmills** [comment]
I think they're discussing the c:\ directory.  If you couldn't create a file anywhere on the c: drive, the machine would be more-or-less unusable.  Perhaps LHDR is trying to write something to the c:\ directory.  You can trace I/O with the utility FileMon.exe.

I run 10K with a group on Tues/Thurs.  I'll load my download onto Windows 10 later and see what I can find.

**Comment by AlvaroHermida** [comment]
Yes, @fcomida , the idea is to separate the code and the data files, so Windows provides some vars like `%PROGRAMDATA%`, `%APPDATA%` and `%LOCALAPPDATA%`, where the developers can safely write their datafiles.  Probably `C:\%PROGRAMDATA%` is the right place for the `saved_parameters.db` and `settings.ini` files, although this goes against the purpose of the _portable_ mode.

Anyway, the portable mode probably only makes sense when installing on a (non-default) user provided folder. I just tested again installing on `E:\bin\Luminance HDR`, and everything works flawlessly, with all the files on the same folder. After moving the folder to a pendrive, the configuration is preserved.

**Comment by fcomida** [comment]
Portable mode is indeed for intalling your portable program in a pendrive, going to visit your best friend, plugging the pendrive in his machine, running the software without touching anything in you friend's computer and happily going home with yet a friend. Since no many friends run Linux, it does only make sense on Windows. And macOS? Maybe?

**Comment by Benitoite** [comment]
@fcomida macOS has application bundles (a special type of folder/dir) that when created carefully, are fully “portable”.  macOS app bundles are not written to during a run, so any .db or .ini that gets created would not be part of the portable bundle, but <s>would</s> should be part of the user’s application support library.

**Comment by fcomida** [comment]
@Benitoite So would copying the bundle folder on a pendrive and checking "Portable mode" in the settings enable the functionality?

**Comment by Benitoite** [comment]
I have tested the portable mode checkbox on Mac, and found that when you restart the program the checkbox becomes unchecked.  I couldn't determine where the program is storing settings.  
Is it usually in ~/.LuminanceHDR ?  I did delete that folder, but don't know where the settings are going at this point.

**Comment by fcomida** [comment]
I guess daniel enabled that only for windows, I'll check the code later.

**Comment by Benitoite** [comment]
I should mention when copied to the thumb drive the option is enabled.

**Comment by fcomida** [comment]
When "Portable mode" is checked the empty file "PortabeMode.txt" is created into QApplication::applicationDirPath() and a new QSetting object is created with this call:  QSettings(QStringLiteral("settings.ini"), QSettings::IniFormat);

As you see we just pass the filename so it will be written into the "current working directory" which usually is the same directory where the executable is (or the cwd of the parent process that started the application).

**Comment by Benitoite** [comment]
Aha! Setting portable mode on the thumb drive does work but you must launch on the command line (that way you actually have a cwd).  Double Clicking the bundle icon to launch after the app has been made portable results in an OOME when loading the tm settings db.

One problem with this is **_files are being written into the bundle_** (Contents/MacOS) which invalidates the code-signature I create when bundling the app. A good solution would be to keep those files in `../../..` relative to the `luminance-hdr` executable. That puts them in the same level as the bundle itself. You might even use `.LuminanceHDR` there too to hide them.

**Comment by fcomida** [comment]
Do you mean .LuminanceHDR inside the same directory of the exe? A portable app shoudn't touch anything on the hosting computer.

**Comment by Benitoite** [comment]
Right, what I mean is have the files not nested inside the bundle where the executable binary is, but to the same level as the bundle on the thumb drive. 
````
Thumbdrive/
    .LuminanceHDR/
          PortableMode.txt
          two other files
    Luminance HDR.app/
          Contents/
                 MacOS/
                      luminance-hdr
                      luminance-hdr-cli
                      align_image_stack
````

**Comment by fcomida** [comment]
@Benitoite please test my changes

**Comment by Benitoite** [comment]
@fcomida Portable mode working on mac, good fix there.  Unfortunately now I get this error message on every start-up in normal mode from the hard drive: 
![screen shot 2018-09-11 at 10 39 01 am](https://user-images.githubusercontent.com/17919239/45377363-3ea97f80-b5af-11e8-933b-7952144206f4.jpg)
Click OK and the program otherwise functions as normal.

**Comment by Benitoite** [comment]
Furthermore, portable mode works on the HD now also w/no error message.

**Comment by fcomida** [comment]
@Benitoite  Now it should be fixed.

**Comment by fcomida** [comment]
@Benitoite It should also work when one calls the executable from a different directory: on Windows and Linux all files (`PortableMode.txt`, `settings.ini` and `saved_parameters.db`) are written in the same directory of the executable, on macOS inside `.LuminanceHDR`, which is created inside the root of the bundle.

**Comment by Benitoite** [comment]
@fcomida As this works now, if I say copy LuminanceHDR-2.5.2 app to `/Applications`, this means `.LuminanceHDR/` gets created in `/Applications`.  This works on my system, however there are two issues.  A user might not have permission to modify `/Applications`, and the settings are system wide.  Would it be possible to use `~/Library/'Application Support'/.LuminanceHDR` instead?  Users always can write there without authenticating.

**Comment by fcomida** [comment]
@Benitoite  In non portable (normal) mode the only file created (`saved_parameters`) is already written somewhere inside the user HOME directory, for portable mode I did as you said in a previous comment (saving everything inside the bundle).

**Comment by Benitoite** [comment]
> already written somewhere inside the user HOME directory
Thanks for the clarifications @fcomida . I must have been seeing the result of clicking portable mode on accident.
However, I cannot find saved_parameters.db on my computer.  It should be, in normal mode, somewhere in the HOME directory.  A search turns up nothing.

**Comment by fcomida** [comment]
@Benitoite I checked the code and Qt5 docs. `QDir::homePath() + .config/.LuminanceHDR` where, on macOS, `QDir::homePath()` returns the content of HOME env variable.

**Comment by Benitoite** [comment]
@fcomida Ok, working normally.  Here is an updated mac build
https://filebin.net/fn5divy9zkbgczzo/Luminance_HDR_2.5.2-TestCC.dmg?t=wo6leu43

**Comment by fcomida** [comment]
@Benitoite thank you for testing it and for the new build. I'm posting the link on fb and closing this.
