### ISSUE TITLE
Can't load Sony Alpha 6000 RAW (.arw) "HdrCreationManager::loadFilesDone(): Error loading a file."

### ISSUE THREAD

**Issue by hrehfeld** [LuminanceHDR/LuminanceHDR#124]
```
$ pacman -Qi luminancehdr 
Name            : luminancehdr
Version         : 2.5.1-12
$ pacman -Q | ag raw
libraw 0.19.0-1
libraw1394 2.1.2-1

```

In the "new HDR Image" Dialog, I can't add/load any of my Sony Alpha's raw files. The message always says:
`"HdrCreationManager::loadFilesDone(): Error loading a file."`

Example RAW: [_DSC0883.zip](https://github.com/LuminanceHDR/LuminanceHDR/files/2328106/_DSC0883.zip)

Maybe originating from here? https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/HdrWizard/HdrCreationManager.cpp#L161

Both Shotwell and Darktable open the raws fine.

**Comment by fcomida** [comment]
@hrehfeld 
 I can open it in Luminance HDR 2.5.1, LibRaw-0.18.13, Fedora 28. Check RAW conversion settings in Preferences->Raw conversion.
![screenshot_20180829_112246](https://user-images.githubusercontent.com/11018726/44778846-495f2000-ab7e-11e8-9ed4-0eaa3ec4a389.png)

**Comment by hrehfeld** [comment]
Hm, that's strange. Maybe a regression in libraw? Do you know how I could easily check for that?
My Raw Conversion settings are these, look fine to me?
![2018-08-29_12-25-53](https://user-images.githubusercontent.com/80887/44782226-d312eb80-ab86-11e8-9cdf-194f613fc64b.png)
![2018-08-29_12-25-41](https://user-images.githubusercontent.com/80887/44782227-d3ab8200-ab86-11e8-9ab6-f1af21457401.png)
![2018-08-29_12-25-22](https://user-images.githubusercontent.com/80887/44782228-d3ab8200-ab86-11e8-8114-3e2db0e27a60.png)

**Comment by fcomida** [comment]
I'll check it with LibRaw 0.19. There's also an issue with exif, it cannot find the EV value.

**Comment by fcomida** [comment]
@hrehfeld I confirm it fails on LHDR 2.5.2, LibRaw 0.19.0

**Comment by fcomida** [comment]
It doesn't actually load any RAW file with LibRaw 0.19.0 !!!

**Comment by heckflosse** [comment]
Not really related to this issue, but worth to mention (not about raw decoders, but about the demosaicers):

There's some work by @CarVac (mainly) and me (less) to make a library for demosaicing raw files based on the [highly optimized code in RT](https://github.com/CarVac/librtprocess)

**Comment by fcomida** [comment]
@heckflosse Cool, the GPL2 and GPL3 demosicing plugins for LibRaw aren't mantained anymore and no longer available in 0.19

**Comment by heckflosse** [comment]
@fcomida I had the same issue. Deactivating noise reduction solved it.

**Comment by nstetter** [comment]
Same problem for me with

```
luminancehdr 2.5.1-13
libraw 0.19.0-1
```

Deactivating noise reduction in the RAW conversion settings didn't help.

**Comment by nstetter** [comment]
@fcomida: I don;t see a setting for 'demosaicing':
![screenshot_20181111_133712](https://user-images.githubusercontent.com/21746115/48313004-e692f780-e5b6-11e8-8976-c564c55cf0e4.png)

**Comment by heckflosse** [comment]
@nstetter Look for `Quality` in the `General` tab

**Comment by nstetter** [comment]
@heckflosse It works with none of Quality settings

**Comment by fcomida** [comment]
@hrehfeld @heckflosse @nstetter LibRaw-0.19.1 seems to have fixed this.
