### ISSUE TITLE
macOS: update align_image_stack

### ISSUE THREAD

**Issue by Benitoite** [LuminanceHDR/LuminanceHDR#125]
https://github.com/LuminanceHDR/LuminanceHDR/blob/master/build_files/platforms/macosx/align_image_stack is currently an old version that doesn’t support the auto crop function.  This could somehow be updated, rebuilt, etc.

I had success moving  from a recent hugin build the bare `align_image_stack` into `build_files/platforms/macosx` and its `.dylib`s into the lhdr bundle. That’s one way to go.

**Comment by fcomida** [comment]
@Benitoite
Can you open a pull request?

**Comment by Benitoite** [comment]
@fcomida 
https://github.com/LuminanceHDR/LuminanceHDR/pull/126 created

**Comment by Benitoite** [comment]
@fcomida 
https://github.com/LuminanceHDR/LuminanceHDR/pull/127 created, adds an additional dylib to Libraries/
