### ISSUE TITLE
TIFF exports are black.

### ISSUE THREAD

**Issue by yowich** [LuminanceHDR/LuminanceHDR#128]
TIFF exports by Luminance HDR do not show anything but are just black. 

Windows 10 64 bit
Windows up to date.

**Comment by Benitoite** [comment]
@yowich what is the version # of the RT app you are testing?

**Comment by yowich** [comment]
What is the RT app?

**Comment by Benitoite** [comment]
So sorry my typo, I meant which version of Luminance HDR?

**Comment by yowich** [comment]
Not a problem. It is 2.5.1. Photoshop opens them and Windows folders show the thumbnail images for them, but FastStone image viewer doesn't. So it might be an issue related to Faststone.

**Comment by Benitoite** [comment]
Ok, feel free to upload a tiff that exhibits the problem for you and we can also test. Btw where did you get the Luminance HDR 2.5.1 ?  Is it the official release version?

**Comment by fcomida** [comment]
No reply so I am closing this.
