### ISSUE TITLE
Abnormal termination without any message.

### ISSUE THREAD

**Issue by yowich** [LuminanceHDR/LuminanceHDR#129]
I ran HDR Creation Wizard for three CR2 files on Windows 10 64-bit with the auto-align turned on. But it is abnormally terminated without a message after a few seconds I click on Finish button on the final stage.

**Comment by fcomida** [comment]
Please try replacing alingn_image_stack.exe with the latest version provided by Hugin:

https://sourceforge.net/projects/hugin/files/hugin/hugin-2018.0/
