### ISSUE TITLE
Build fails with non-obvious relative path to source

### ISSUE THREAD

**Issue by mwoehlke** [LuminanceHDR/LuminanceHDR#13]
I have the following setup:

```
CMAKE_SOURCE_DIR = /usr/local/src/.../LuminanceHDR
CMAKE_SOURCE_DIR = /usr/local/build/.../LuminanceHDR
    → /var/local/build/.../LuminanceHDR
```

This fails to compile with errors like:

```
moc_<whatever>.cpp: fatal error: ../../../../../src/.../LuminanceHDR/.../<whatever>.h: No such file or directory
 #include "../../../../../src/.../LuminanceHDR/src/.../<whatever>.h"
```

There is indeed no such file:
  `/usr/local/build/.../LuminanceHDR/src/.../../../../../../src/.../LuminanceHDR/...`
 → `/var/local/build/.../LuminanceHDR/src/.../../../../../../src/.../LuminanceHDR/...`
 → `/var/local/src/.../LuminanceHDR/...`
...which does not exist.

The problem is that you are making moc work too hard to find this file. I don't normally run into this problem (i.e. with other projects) because most Qt projects have the "local" directories as includes.

Two possible solutions:
1. In each directory that has MOC'd headers: `include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR})`
2. `set(CMAKE_INCLUDE_CURRENT_DIR ON)`

**Comment by davideanastasia** [comment]
Can you send a pull request?
