### ISSUE TITLE
Use amaze demosaic from librtprocess

### ISSUE THREAD

**Issue by heckflosse** [LuminanceHDR/LuminanceHDR#130]
As a first version of [librtprocess](https://github.com/CarVac/librtprocess) now is available, I will start a new branch to integrate librtprocess.
This is especially important because latest libraw version does not support amaze demosaic anymore.
It will also allow to use the raw ca correction from librtprocess (which is the same as in RawTherapee) in a next step.

**Comment by fcomida** [comment]
@heckflosse great. In the meantime I'll have to fix LHDR for LibRaw 0.19.

**Comment by fcomida** [comment]
@heckflosse Hey Ingo, any basic, ready to use image processing algos in RawTherapee (convolutional filters, dilate/erode, ...) I can steal? An Image processing library (VIPS?) you recommend?

**Comment by heckflosse** [comment]
@fcomida Hi Franco, what do you need? ;-)

**Comment by heckflosse** [comment]
@fcomida I wrote motion detection code for pixelshift raw files, but this code requires perfect alignment between the frames, same exposure for all frames and also that the frames have a bayer pattern. 

I don't think it can be easily used in lhdr because the requirements are too different.

**Comment by fcomida** [comment]
@heckflosse I mainly need low level generic algos (basic image processing stuff).

**Comment by heckflosse** [comment]
@fcomida Maybe you can use stuff from [cimg](https://github.com/dtschump/CImg)

**Comment by fcomida** [comment]
@heckflosse I found this project: 

https://github.com/banterle/HDR_Toolbox/blob/master/README.md

HDR Toolbox is a MATLAB/Octave toolbox for processing High Dynamic Range (HDR) content.

I'll have a look at `cimg`, `VIPS (libvips)` is another such library.

**Comment by heckflosse** [comment]
@fcomida I think we should close this issue and create a new one to start integrating librtprocess from scratch. ok?

**Comment by fcomida** [comment]
@heckflosse go ahead, I'll branch master and push "librtprocess-integration" for doing the work.

**Comment by heckflosse** [comment]
Ok
