### ISSUE TITLE
Russian translation lost

### ISSUE THREAD

**Issue by prokoudine** [LuminanceHDR/LuminanceHDR#131]
It looks like at some stage you lost the existing translation into Russian: there is not a single translated message in the lang_ru.ts file. I'm not sure if that applies to other translation, but you might want checking your update scripts or whatever could cause that. I'll see if I can restore data from an older release.

**Comment by fcomida** [comment]
@prokoudine I had a problem with the trasifex client. I downloaded the russian translation from Transifex and replaced lang_ru.ts in Luminance HDR (`tx pull` didn't work) . 
Recompiling I got this:

**Updating '/home/franco/src/new/LuminanceHDR/Build2/lang_ru.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 952 translation(s) (952 finished and 0 unfinished)
    Ignored 210 untranslated source text(s)**

**Comment by prokoudine** [comment]
Thank you :)
