### ISSUE TITLE
Rectangle patches

### ISSUE THREAD

**Issue by afr-e** [LuminanceHDR/LuminanceHDR#132]
**OS**:
win10

**Build**:
https://keybase.pub/gaaned92/HDRNightlyBuilds/Luminance-HDR_master_v.2.5.1-241-g5f582a3e_WinVista_64.zip

**Files**:
https://discuss.pixls.us/t/play-raw-maritime-museum/8969

**Steps**:
1. New HDR Image from `_8237005.ORF`, `_8237002.ORF` and `_8237004.ORF`. I get this

![image](https://user-images.githubusercontent.com/42004791/45437923-cf518f80-b683-11e8-96ee-9e53534211c7.png)

2. Take EV values from HDRMerge and enable auto anti-ghosting.

![image](https://user-images.githubusercontent.com/42004791/45438101-48e97d80-b684-11e8-86f9-28d1797b7303.png)

3. Save 32f TIF as `_8237002-_8237005-Weights= Triangular - Response curve= Linear - Model= Debevec.tif`

4. _Brightened_ result (below is the left half of the image due to upload size limitation).

![rects](https://user-images.githubusercontent.com/42004791/45438710-d5e10680-b685-11e8-9690-b93bad201f1a.jpg)

**Comment by afr-e** [comment]
**PS** the posters of

- https://discuss.pixls.us/t/play-raw-maritime-museum/8969
- https://discuss.pixls.us/t/play-raw-maritime-museum/8969/26

don't seem to have encountered this issue.

**Comment by Benitoite** [comment]
> * https://discuss.pixls.us/t/play-raw-maritime-museum/8969/26

Did get the same EXIF warning. I assigned a bracket of [2,-2,0] to the raws according to how bright they looked.  LHDR's default 2-stop-apart assignment was in the incorrect order and resulted in a negative result.

**Comment by Beep6581** [comment]
I tested using a self-compiled `v.2.5.1-249-g`bdadfc75 in Linux.

No missing Exif warning.
![screenshot_20180912_192523](https://user-images.githubusercontent.com/5844619/45442187-9cc68780-b6c1-11e8-8dd0-eaafa86d6a49.png)

Auto-antighosting never worked well for me, ever. The blocky artifacts are caused by it, clearly visible in LHDR's HDR preview.

**Comment by Beep6581** [comment]
The exposure values returned by HDRMerge `continuous-50-g`fd69a2a are: 0, 3.59, 5.43. When using those in LHDR, with auto-antighosting disabled, I get a correct HDR image.
![screenshot_20180912_193534](https://user-images.githubusercontent.com/5844619/45442719-16ab4080-b6c3-11e8-9b1b-7c02213a6687.png)

Auto anti-ghosting does not work and in my opinion should be removed from the UI.
* https://sourceforge.net/p/qtpfsgui/bugs/182/
* #37

**Comment by afr-e** [comment]
Thanks. I will disable auto anti-ghosting. FYI, I was using `https://keybase.pub/gaaned92/HDRNightlyBuilds/HDRmerge_master_continuous-34-g148c8e0_release_64.zip`.
