### ISSUE TITLE
Crash using White Balance

### ISSUE THREAD

**Issue by montex** [LuminanceHDR/LuminanceHDR#134]
Hello, 

I am reporting a bug signaled by Ubuntu users:
https://bugs.launchpad.net/ubuntu/+source/luminance-hdr/+bug/1791507 

Basically, if clicking on "White Balance" as the first operation after the HDR image is created, the program crashes.

I am attaching the output of gdb during the operation, although I ran the program without debug symbols:
[gdb-luminance-hdr.txt](https://github.com/LuminanceHDR/LuminanceHDR/files/2500194/gdb-luminance-hdr.txt)

**Comment by fcomida** [comment]
I'm closing this as duplicate of #135
