### ISSUE TITLE
Problems loading Pentax K-1 mk 2 files

### ISSUE THREAD

**Issue by grahamdicker** [LuminanceHDR/LuminanceHDR#139]
graham@mozart:~> rpm -qa | grep -i 'luminance\|libraw'
luminance-hdr-2.5.1-1.146.x86_64
libraw16-0.18.9-119.4.x86_64
libraw15-0.17.1-23.1.x86_64
libraw19-0.19.0-125.2.x86_64
libraw-devel-0.17.1-23.1.x86_64
libraw1394-11-2.1.0-8.3.x86_64

Opensuse 42.3

Trying to load K-1 mark 2 files mostly results in HdrCreationManager::loadFilesDone(): Error or a crash out. Turning off noise reduction as recommended in a previous post improved the ability to load slightly (some images now load) but still having major problems. I can't upload a test file as they are bigger than 10MB. A typical file can be got from here: https://www.dropbox.com/s/0b7qckre5hl6weh/imgp0821.zip?dl=0

**Comment by fcomida** [comment]
LibRaw 0.19 dropped GPL2/GPL3 demosicing packs (AMAZE etc.). If you've been using one of those open Preferences->Raw Settings and select a supported demosicing method.
This doesn't solve the issue of opening RAW files completely. For me opening first a HDR file (or creating one from jpegs or tiffs) do the trick. Subsequent reading of RAW files works again :O
It's a dirty and annoying trick. The only solution for now is linking to an older version of LibRaw.

**Comment by grahamdicker** [comment]
Thank you fcomida it is now working OK using using your recommended changes and procedure. I am most grateful.
