### ISSUE TITLE
Patent

### ISSUE THREAD

**Issue by logixoul** [LuminanceHDR/LuminanceHDR#141]
Hi. :)

I have a question.
Luminance HDR implements Durand's tonemapping algorithm, which is patented in the US:
https://patents.google.com/patent/US7146059

Have you guys gotten permission for implementation from the patent owner?

Thanks in advance :)

**Comment by Benitoite** [comment]
LHDR uses the Mantiuk/Krawczyk implementation, which is different than Durnad's free MIT code, (which you would expect to be closer to the patented mathematics—code that MIT publishes free anyway with their own clauses.)

**Comment by fcomida** [comment]
Durand method is patented in the US and the patent owner (MIT???) does not enforce it.
Software patents suck!!!
