### ISSUE TITLE
Speedup for KimKautz tmo

### ISSUE THREAD

**Issue by heckflosse** [LuminanceHDR/LuminanceHDR#144]
This issue is about a speedup for KimKautz tone mapping operator.

I start with measuring current processing time on my rusty AMD FX8350 using a 24MP file.

Current processing time: ~9460 ms

**Comment by heckflosse** [comment]
First commit reduces processing time to ~5570 ms by using xlogf and xexpf from sleef

**Comment by heckflosse** [comment]
Second commit reduces provessing time to ~1430 ms by using `findMinMaxPercentile(..)`

**Comment by fcomida** [comment]
Impressive, as always ;)
Thank you.

**Comment by heckflosse** [comment]
More commits will follow. I will create a PR when completed.

**Comment by heckflosse** [comment]
4th commit reduces processing time to ~500 ms by using SSE code for expensive loops

**Comment by heckflosse** [comment]
5th commit reduces processing time to ~370 ms
