### ISSUE TITLE
Vanhateren speedup

### ISSUE THREAD

**Issue by heckflosse** [LuminanceHDR/LuminanceHDR#147]
This issue is about a speedup for Vanhateren tone mapping operator.

I start with measuring current processing time on my rusty AMD FX8350 using a 24MP file.

Current processing time: ~13520 ms

**Comment by gaaned92** [comment]
@heckflosse in `pacman.conf`, don't forget  `IgnorePkg   =  mingw-w64-x86_64-boost`

**Comment by heckflosse** [comment]
First commit reduces processing time to ~11250 ms by using xlogf and xexpf from sleef and vectorizing applyGamma()

**Comment by heckflosse** [comment]
Second commit reduces processing time to ~500 ms by using a lookup table in the main loop

**Comment by heckflosse** [comment]
Third commit reduces processing time to 440 ms
