### ISSUE TITLE
Add support for HTML export

### ISSUE THREAD

**Issue by lapo-luchini** [LuminanceHDR/LuminanceHDR#15]
Would be nice to also wrap the [pfsouthdrhtml](http://pfstools.sourceforge.net/hdrhtml.html) functionality. The slider is so smooth and nice.
(I wonder in the same technique could be used to have a smooth slider inside Luminance itself, too)

**Comment by fcomida** [comment]
Added in hdrhtml branch. Please do some tests, thank you.

**Comment by fcomida** [comment]
Functionality added in development branch. It will be available in next release so I'm closing this issue.
