### ISSUE TITLE
Inconsistent results between preview window and what is saved/exported

### ISSUE THREAD

**Issue by Davide-sd** [LuminanceHDR/LuminanceHDR#155]
I'm here to report a problem (or at least what it seems to me to be a problem, maybe I'm wrong).

Today I took a few shots in a hurry at the sunset. I loaded them into Luminance (2.5.1), using the default exposures and I have enabled "Auto-align" and "Auto-crop" because I took them without a tripod. Then I selected Fattal, with the following settings:

Alpha: 1.25
Beta: 0.92
Color Saturation: 1.20
Noise Reduction: 0.00
Pre-Gamma: 0.66

Unfortunately, the exported or saved final image is different from the result shown in the preview window!!!! I saved and fast exported several times, and the image saved is almost always brighter than what is seen on the preview window! I said almost, because in one occurence it did save quite close to what was seen in the preview.

[Here you will find the archive with the NEF files](https://www.dropbox.com/s/9984itbi49j884m/DSC_0017-8-9.zip?dl=0) I used to create the HDR, as well as 3 pictures that shows what I'm talking about.

**Comment by Benitoite** [comment]
@Davide-sd What is your HDR profile/settings? Operating System / Color Management settings?
![screen shot 2019-01-05 at 11 12 12 am](https://user-images.githubusercontent.com/17919239/50728240-8f536400-10db-11e9-88fa-4885a1c1c88f.jpg)
My quick macOS test yielded consistently slightly brighter in the shadows with jpeg & 16b tiff outputs; it is very, very subtle on my test...
