### ISSUE TITLE
Available demosaicers

### ISSUE THREAD

**Issue by heckflosse** [LuminanceHDR/LuminanceHDR#157]
Currently the following raw demosaicers can be used in lhdr
![grafik](https://user-images.githubusercontent.com/13733487/51272498-89f2f500-19ca-11e9-8221-978980e943f4.png)

Do we need all of them? I ask, because currently I'm moving a lot of demosaicers from rawtherapee to [librtprocess](https://github.com/CarVac/librtprocess)

Edit: Currently the following demosaicers are available in librtprocess

amaze_demosaic
dcb_demosaic
igv_demosaic
lmmse_demosaic
rcd_demosaic
vng4_demosaic
markesteijn_demosaic
xtransfast_demosaic

The dual-demosaicers will follow soon

For bayer:
amaze+vng4
dcb+vng4
rcd+vng4

For xtrans:
markesteijn3pass+fast
markesteijn1pass+fast

**Comment by fcomida** [comment]
With LibRaw 0.19 only these four are available:

![screenshot_20190117_160326](https://user-images.githubusercontent.com/11018726/51327477-b281fa00-1a71-11e9-99b6-78724e367f10.png)
