### ISSUE TITLE
missing tonemap panel

### ISSUE THREAD

**Issue by seviour** [LuminanceHDR/LuminanceHDR#158]
Hello,
Recently I did something that removed my tonemap pannel. Any guide how can I get it back?

**Comment by Benitoite** [comment]
![screen shot 2019-02-06 at 1 17 00 pm](https://user-images.githubusercontent.com/17919239/52374319-cd60e200-2a11-11e9-9f1e-85c7b1dd8000.png)

**Comment by seviour** [comment]
Thank you Benitoite. Sorted :1st_place_medal:
