### ISSUE TITLE
No Menu in LuminanceHDR 2.4.0

### ISSUE THREAD

**Issue by ullix** [LuminanceHDR/LuminanceHDR#16]
I am new to LuminanceHDR and started with installing 2.3.0-3build1 on Ubuntu Trusty. The program has a menu, which has a few items more than the Main Toolbar. In particular the menu provides a Help entry, which I had used.

But then I upgraded to 2.4.0-trusty~ppa1 from the Philipp Johnson ppa (ppa:philip5/extra) and this version has no menu, only a Main Toolbar. 

But worse, when you fiddle in the program and accidentally uncheck the Main Toolbar, then it is gone and you have no way to recreate it, except for reinstalling the whole package.

Hope this is a bug and not a new feature?

How can I get the menu on 2.4.0 and most importantly for me the Help info?

**Comment by fcomida** [comment]
May it be that in unity application menus are moved on top of user screen?

**Comment by ullix** [comment]
I am using the Cinnamon desktop, where the menus are where the are supposed to be ;-)

This is, what it looks like for 2.4.0:
![auswahl_025](https://cloud.githubusercontent.com/assets/9335726/11891514/9cfb540e-a55f-11e5-8748-511c29cf5244.png)

and this is version 2.3.0
![auswahl_026](https://cloud.githubusercontent.com/assets/9335726/11891549/e9263f56-a55f-11e5-88ed-737c28b88880.png)

**Comment by fcomida** [comment]
Is appmenu-qt5 installed? I found this old bug report: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

**Comment by ullix** [comment]
Yes, both appmenu-qt and appmenu-qt5 are installed:

appmenu-qt: 0.2.7+14.04.20140305-0ubuntu1
appmenu-qt5: 0.3.0+14.04.20140415-0ubuntu1

**Comment by fcomida** [comment]
well try removing them, let me know if it works.

**Comment by ullix** [comment]
I removed appmenu-qt5 and  - voila - there is a menu !
Sounds strange that removing an option brings the function back. 
Thanks anyway ;-))

**Comment by fcomida** [comment]
Welcome!!! I guess appmenu-qt5 is for supporting DEs that have an option to move app menus to global such as unity and now plasma 5. I do not know how it is configured outside those DEs, you better contact Cinnamon guys to fix this issue.
