### ISSUE TITLE
Wrong tooltip for highlights clipping methods

### ISSUE THREAD

**Issue by mikhirev** [LuminanceHDR/LuminanceHDR#167]
Hi!

In the preferences dialog, there are the following highlight clipping methods: "Solid White", "Do not transform", "Blend" and "Reconstruct". Although in the tooltip these methods are listed with different names: "Solid white", "Unclip", "Blend" and "Rebuild".

**Comment by fcomida** [comment]
@mikhirev Well spotted!!!
