### ISSUE TITLE
Exposure value limited to -10 / 10 in HDR Wizard

### ISSUE THREAD

**Issue by travnick** [LuminanceHDR/LuminanceHDR#17]
I wonder why EV is limited to -10/10
https://github.com/LuminanceHDR/LuminanceHDR/blob/5cbdbed00d5461fa837cf590330fedf9d59b73c0/src/HdrWizard/HdrWizard.ui#L359

I have images that exceed that values e.g. 13EV so I'm unable to enter that value.

**Comment by supertobi** [comment]
I've seen this blog post, where he used 15 stops:
http://adaptivesamples.com/2015/11/09/hdri-mpumalanga-veld/

I think changing the limit to -20/20 should be fine.

**Comment by jgoffredo** [comment]
I have the same problem, and I want to join, again, to improve the Luminance HDR.

Now I am working to change this limit to -20...+20

**Comment by jgoffredo** [comment]
Worked fine in my test.

**Comment by fcomida** [comment]
Fixed in master.
