### ISSUE TITLE
Batch HDR introduces glitches in pictures

### ISSUE THREAD

**Issue by jmbouffard** [LuminanceHDR/LuminanceHDR#173]
I'm running Luminance 2.5.1 on Windows 10.
When running a batch creation of HDR files, the results on some of the files contain glitches. The most common are a bunch of horizontal lines of various colors (see included sample) but I also saw a bunch of black dots on some occasions.

If I re-create the exact same HDR image using the UI (not the batch) with the same parameters, it creates the HDR with no glitch. Interestingly, if I re-run the exact same batch process with the same files and parameters, the glitches may appear on different files. On my 15 files process, I usually get 2-3 with glitches, not always the same files.

![Capture](https://user-images.githubusercontent.com/4948555/57985241-11ad4680-7a33-11e9-9ae1-fdeb53e0c0df.PNG)

**Comment by heckflosse** [comment]
@jmbouffard Can you try the latest Windows build please?
https://keybase.pub/gaaned92/HDRNightlyBuilds/Luminance-HDR_master_v.2.5.1-384-g7d8b3b4e_WinVista_64.exe

**Comment by jmbouffard** [comment]
@heckflosse I installed the provided build and ran the same process over my 45 files (15 pictures) and all hdr and tone mapped images turned out ok.
The only thing with the new build is that I cannot save the tonemap parameters for re-use in the batch process. The UI panel to save settings and the UI panel for "Fast Export" are nowhere to be found.

**Comment by fcomida** [comment]
@jmbouffard saving hdr fusion custom parameters (custom response curve included) and re-using them in Batch HDR should now work.
If you can do some testing it'd be great, thank you.

**Comment by jmbouffard** [comment]
@fcomida I can can do some testing soon for sure but would need to know where I can get the latest build with the included fix?

**Comment by fcomida** [comment]
@jmbouffard we just released 2.6.0 which has all this fixes. Get it from sorceforge as usual.

**Comment by jmbouffard** [comment]
@fcomida I tried the same "batch HDR" process with the same 45 original files to get 15 HDR files. Then I ran the "batch tone mapping" on all 15 images. All final tone mapped JPG images where created with no glitch. So it seems that for this example the issue is fixed. Thanks.
