### ISSUE TITLE
Unable to load Pentax .PEF files

### ISSUE THREAD

**Issue by milescrawford** [LuminanceHDR/LuminanceHDR#18]
When I attempt to load RAW files from my Pentax K-S1, Luminance crashes completely with the following output on the terminal:

Database opened 
void HdrWizard::resizeEvent(QResizeEvent*) 
void HdrWizard::resizeEvent(QResizeEvent*) 
"Checking /Users/mcrawfor/Desktop/IMGP1724.PEF" 
"Schedule loading for /Users/mcrawfor/Desktop/IMGP1724.PEF" 
"Checking /Users/mcrawfor/Desktop/IMGP1725.PEF" 
"Schedule loading for /Users/mcrawfor/Desktop/IMGP1725.PEF" 
"Loading data for /Users/mcrawfor/Desktop/IMGP1724.PEF" 
"Loading data for /Users/mcrawfor/Desktop/IMGP1725.PEF" 
[gamma0: 0.416667, gamma1: 12.92, 4-Color RGB: 0, Fuji Rotate: -1, User Quality (Demosaicing method): 10, Median Filter Passes: 0, WB Method: 1, WB Temp: 6500, WB Green: 1, Highlight Method: 0, Highlight Rebuild: 0, Black Level: N/A, Saturation: N/A, Auto Brightness: 0, Auto Brightness Threshold: 0.001, Brightness: 1, Noise Reduction: ON, Noise Reduction Threshold: 100, Chromatic Aberation: 0]
[gamma0: 0.416667, gamma1: 12.92, 4-Color RGB: 0, Fuji Rotate: -1, User Quality (Demosaicing method): 10, Median Filter Passes: 0, WB Method: 1, WB Temp: 6500, WB Green: 1, Highlight Method: 0, Highlight Rebuild: 0, Black Level: N/A, Saturation: N/A, Auto Brightness: 0, Auto Brightness Threshold: 0.001, Brightness: 1, Noise Reduction: ON, Noise Reduction Threshold: 100, Chromatic Aberation: 0]
/Users/mcrawfor/Desktop/IMGP1725.PEF: data corrupted at 160391
/Users/mcrawfor/Desktop/IMGP1724.PEF: data corrupted at 160194
"Cannot load /Users/mcrawfor/Desktop/IMGP1724.PEF: Error Unpacking RAW File" 
"Cannot load /Users/mcrawfor/Desktop/IMGP1725.PEF: Error Unpacking RAW File" 
Data loaded ... move to internal structure! 
Segmentation fault: 11

I have also attached the OSX error report output to this issue:
[luminance-crash.txt](https://github.com/LuminanceHDR/LuminanceHDR/files/96459/luminance-crash.txt)

**Comment by fcomida** [comment]
Load just fine in Linux, LibRaw 0.17-2

**Comment by fcomida** [comment]
I fixed Luminance crashing when LibRaw fails to decode a file. A raw file not properly decoded/supported is a LibRaw issue, we can try to deal with LibRaw guys in such a case to see if it can be fixed upstream.
Thank you for reporting it, I'm closing this issue now.
