### ISSUE TITLE
FITS as source files for new HDRs

### ISSUE THREAD

**Issue by prokoudine** [LuminanceHDR/LuminanceHDR#184]
Shouldn't it be possible to use FITS files as source images for building a new HDR image? Currently, the file format is unavailable in supported types when you add images in the HDR wizard.

**Comment by fcomida** [comment]
@prokoudine There's a FITS importer but apparently nobody has never used it. If you are gonna playing with astrophotography I'm sure there's a lot to polish and fix there. Any feedback is very much needed.

**Comment by fcomida** [comment]
@prokoudine FITS support is optional. If CMAKE finds the cfitsio library it'll enable it.

**Comment by fcomida** [comment]
![eagle_nabula](https://user-images.githubusercontent.com/11018726/59389273-3bc20200-8d6e-11e9-8a36-08f56ddc9b43.jpg)

**Comment by prokoudine** [comment]
But that's not what I'm saying at all :)))

I know I can open a FITS file. But I can't stack multiple FITS files in the wizard. There's simply no such file format filter in the Add File dialog.

**Comment by fcomida** [comment]
@prokoudine That's because you can only find FITS files that contain "astro" data :)))

Opening FITS files in the wizard has no use.

**Comment by fcomida** [comment]
@prokoudine I mean, FITS is a very capable image file format like TIFF (I think it's an extension of TIFF or vice-versa). So it's possible to save all kind of data in a FITS. To my knowledge nobody uses it for "regular" photography and "astro" photography is very different in many ways.

**Comment by fcomida** [comment]
@prokoudine I'm gonna close this one. Feel free to reopen it if you have more information on how to open FITS files in the wizard. Thank you.
