### ISSUE TITLE
Add Repology badge

### ISSUE THREAD

**Issue by luzpaz** [LuminanceHDR/LuminanceHDR#187]
Repology shows what repositories a package is available in. For space purposes the small badge is appropriate here. Example:
[![Packaging status](https://repology.org/badge/tiny-repos/luminance-hdr.svg)](https://repology.org/project/luminance-hdr/badges)

But in other contexts, the full badge is more informative. Example:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/luminance-hdr.svg?header=luminance-hdr)](https://repology.org/project/luminance-hdr/versions)

Let me know and I will make a PR if you're interested

**Comment by fcomida** [comment]
@luzpaz Sure, I am interested, thank you.
