### ISSUE TITLE
Compiling on CentOS 7 (with workaround)

### ISSUE THREAD

**Issue by mattebb** [LuminanceHDR/LuminanceHDR#195]
Hi, I'm working in a visual effects studio and I've just tried building Luminance HDR on CentOS 7 (which is pretty much the standard linux distro for vfx).

I was able to get all the dependencies installed, and attempted to build the latest git master, but it failed in the ashikhmin tone mapping operator due to its usage of OpenCL [1]. CentOS 7 uses gcc 4.8.5 so it's probably missing a lot of new OpenCL features.

Just for fun though, I tried commenting out the ashikhmin operator in ToneMappingOperators/CMakeLists.txt and in Libpfs/tm/ToneMappingOperator.cpp line 369. This worked and allowed me to build successfully and the application seems to run well (although obviously the ashikhmin operator doesn't work). We're interested in using Luminance HDR for building HDR light probes so tone mapping doesn't matter to us that much.

Just letting you know - it would be great if there was a workaround for this that doesn't involve us maintaining a local patch, since I'm sure other studios would run into the same issue. Eg. an alternate code path, or a configurable way at build time to disable the code in question. Or do you have any other suggestions that might work?

thanks!

Matt

[1]
`[ 11%] Building CXX object src/TonemappingOperators/CMakeFiles/pfstmo.dir/ashikhmin02/tmo_ashikhmin02.cpp.o
/syd_home/mebb/Documents/code/LuminanceHDR/src/TonemappingOperators/ashikhmin02/tmo_ashikhmin02.cpp: In function ‘void getMaxMin(pfs::Array2Df*, float&, float&)’:
/syd_home/mebb/Documents/code/LuminanceHDR/src/TonemappingOperators/ashikhmin02/tmo_ashikhmin02.cpp:140:73: error: ‘maxLum’ has invalid type for ‘reduction’
     #pragma omp parallel for reduction(min:minLum) reduction(max:maxLum)
                                                                         ^
/syd_home/mebb/Documents/code/LuminanceHDR/src/TonemappingOperators/ashikhmin02/tmo_ashikhmin02.cpp:140:73: error: ‘minLum’ has invalid type for ‘reduction’
make[2]: *** [src/TonemappingOperators/CMakeFiles/pfstmo.dir/ashikhmin02/tmo_ashikhmin02.cpp.o] Error 1
make[1]: *** [src/TonemappingOperators/CMakeFiles/pfstmo.dir/all] Error 2
`

**Comment by heckflosse** [comment]
@mattebb 
https://linuxhostsupport.com/blog/how-to-install-gcc-on-centos-7/

**Comment by heckflosse** [comment]
@mattebb I will try to make a patch today

**Comment by heckflosse** [comment]
@mattebb I pushed a fix. Can you please test if it builds now?

**Comment by mattebb** [comment]
Thank you very much! I just tried it back at the office this morning and it worked perfectly.

I did have one other different compile error though with the latest git master:

/syd_home/mebb/Documents/code/LuminanceHDR/src/HdrCreation/robertson02.cpp: In member function ‘void libhdr::fusion::RobertsonOperatorAuto::computeResponse(libhdr::fusion::ResponseCurve&, libhdr::fusion::WeightFunction&, libhdr::fusion::ResponseChannel, const DataList&, float*, size_t, size_t, float, float, const float*)’:
/syd_home/mebb/Documents/code/LuminanceHDR/src/HdrCreation/robertson02.cpp:355:31: error: call of overloaded ‘isnan(double&)’ is ambiguous
         } else if (isnan(delta) ||
                               ^

I saw this response https://stackoverflow.com/questions/33770374/why-is-isnan-ambiguous-and-how-to-avoid-it and replace isnan() with ::isnan() and it allowed it to compile.

cheers

**Comment by fcomida** [comment]
@mattebb thank you, fixed in master.

**Comment by mattebb** [comment]
Thanks very much!
