### ISSUE TITLE
AVAST Anti-Virus ware says your 2.6.0 hdr.exe is infected with: IDP.GENERIC

### ISSUE THREAD

**Issue by tkjtkj** [LuminanceHDR/LuminanceHDR#197]
My AVAST anti-virus, upon installing your hdr.exe 2.6.0 into Win7 , says it's infected with the IDP.GENERIC  virus , so i moved your exe to a safe place, pending your confirming that AVAST is wrong ...

tkjtkj@gmail.com

**Comment by fcomida** [comment]
@tkjtkj where did you get the installer from?

**Comment by fcomida** [comment]
@gaaned92 Any idea?

**Comment by gaaned92** [comment]
There is nothing named hdr.exe in my builds! And they should not be detected as I have avast on my PC. I use to send to their lab the suspected files.
I don't have any idea what it is.
When I had AVAST installed on my PC, I used to send to their lab the suspected files.

**Comment by fcomida** [comment]
@gaaned92 There are lots of sites where one can download all kind of software from (included LHDR). I guess @tkjtkj got it from one of those sites.
@tkjtkj Please download the official installer from SourceForge.
