### ISSUE TITLE
IOWorker: TiffReader: unsupport  photometric type

### ISSUE THREAD

**Issue by Taichi-Pink** [LuminanceHDR/LuminanceHDR#202]
When I click "Open HDR Images" and open the .tif image, I met this problem. But I think LHDR should and could open the .tif format images. Can someone help me? Thanks !!!
![image](https://user-images.githubusercontent.com/30882053/63785319-64f22900-c8ad-11e9-9ce8-8aba901eab69.png)

**Comment by fcomida** [comment]
@Taichi-Pink Why do you think LHDR could or should support your TIFF file? Can you tell us its actual PHOTOMETRIC TYPE? We support RGB, SEPARATED (CMYK) and LOGLUV types. If your TIFF differs please convert it to a type LHDR can handle.

**Comment by Taichi-Pink** [comment]
When I opened images, I found LHDR support .tiff format, so I thought LHDR could open .tiff images.
![image](https://user-images.githubusercontent.com/30882053/63963117-8b50c980-ca51-11e9-967d-26907d7919df.png)
May I ask how to check the PHOTOMETRIC TYPE of tiff images?

**Comment by fcomida** [comment]
@Taichi-Pink You can think of TIFF as a sort of container for any kind of data. So you can have bitonal (black and white) images (from fax/scanners) stored in a TIFF file or multiple images stored in the same file.
Which OS are you using? On Linux or macOS there's the "tiffinfo" utility (part of libtiff-tools). ImageMagick is a great suite for comverting/

**Comment by Taichi-Pink** [comment]
Thank you!! My os is Ubuntu. And I use Matlab change rewrite my .tiff file, it works!!
The PHOTOMETRIC TYPE now is RGB, which I duplicated the original .tiff file to 3-channels. 

Thanks again!
