### ISSUE TITLE
Unable to create hdr image from wizard in 2.6.0

### ISSUE THREAD

**Issue by sorc17** [LuminanceHDR/LuminanceHDR#203]
Button "Compute" in hdr creation wizard do nothing just show hdr preview dialog. Button "Cancel" closes wizard. How to create hdr image? Where is "Finish" button? Do I miss something? Same example in 2.5.1 works great - I just press "Finish" button and hdr image created.

Linux localhost.localdomain 5.2.13-200.fc30.x86_64 #1 SMP Fri Sep 6 14:30:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

![Selection_001](https://user-images.githubusercontent.com/16558421/65379720-76282d00-dcd5-11e9-8e95-feb8c1f38d45.jpg)
![Selection_002](https://user-images.githubusercontent.com/16558421/65379722-7aece100-dcd5-11e9-9279-8b20a5ae35c0.jpg)
![Selection_003](https://user-images.githubusercontent.com/16558421/65379724-7f18fe80-dcd5-11e9-9102-c6da1c9e471e.jpg)
![Selection_004](https://user-images.githubusercontent.com/16558421/65379726-8213ef00-dcd5-11e9-85e8-6b9f6e711e06.jpg)

**Comment by fcomida** [comment]
@sorc17 uncheck "Show HDR Preview" checkbox. I know, it's not very intuitive. It's been already changed in 'master', where you can now 'accept' the computed HDR from the preview window.

**Comment by sorc17** [comment]
Thanks! Sorry I forgot to close issue earlier.
