### ISSUE TITLE
--hdrCurveFilename ambiguous

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#208]
`v.2.6.0-249-g`77752acd

The CLI parameter `--hdrCurveFilename` is ambiguous - it does not contain the words "input" nor "output", making one assume it works for both input and output. That is not the case, it works only for input:
https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/MainCli/commandline.cpp#L587

Please rename it to `--hdrCurveInputFilename` (or `--inputCameraResponseCurve`), and add a new `--hdrCurveOutputFilename` (or `--outputCameraResponseCurve`).

Ref:
https://discuss.pixls.us/t/write-response-curve-from-command-line/14228

**Comment by fcomida** [comment]
@Beep6581 I'm gonna sort all this mess out as soon as possible. Thanks again.

**Comment by Beep6581** [comment]
Fix confirmed in f7edae38.
