### ISSUE TITLE
Update to qt packages in Ubuntu 14.04 removed Luminance HDR

### ISSUE THREAD

**Issue by judj** [LuminanceHDR/LuminanceHDR#21]
Hi, an update to qt packages in Ubuntu 14.04 just occured. When I rebooted my computer, Luminance HDR was removed. When I tried to reinstall it, a list of unresolved packages came up. I'm on a 64 bit machine using the Highly Explosive PPA.

**Comment by fcomida** [comment]
Ubuntu issue, not ours, I'm closing it.
