### ISSUE TITLE
HDR image can not be saved

### ISSUE THREAD

**Issue by Newbie1945** [LuminanceHDR/LuminanceHDR#220]
I installed Luminance HDR 2.6.0   in Ubuntu 20.04  by pressing the blue install button at the website
https://www.flathub.org/apps/details/net.sourceforge.qtpfsgui.LuminanceHDR
I then tried Interactive HDR creation as explained on the website
https://luminancehdr.readthedocs.io/en/latest/creating_hdr/interactive/
I loaded five HDR-images I had made and then I pressed the next button, I came in the 'Choose settings for HDR creation window’, I did not change any of the settings and pressed the Compute button
and then I came in a HDR Preview window, after I closed this window I was back in the 'Choose settings for HDR creation window’ . I could not save the HDR-image.
After I pressed cancel I was back in the Luminance main window, The save button in the window was not highlighted like  ‘New HDR image’, pressing this ‘save button’ did not give any response.

**Comment by fcomida** [comment]
Sorry that GUI is not intuitive at all. Please uncheck the "HDR preview"
checkbox for getting the final result.

Il mar 28 lug 2020, 16:59 Newbie1945 <notifications@github.com> ha scritto:

**Comment by Newbie1945** [comment]
Thanks fcomida, I now could save the HDR

**Comment by Newbie1945** [comment]
Thanks, problem solved
Marius


Franco Comida schreef op 2020-07-28 17:41:
