### ISSUE TITLE
How to create "Tone Mapping Settings" & Where are they stored?

### ISSUE THREAD

**Issue by verbal007** [LuminanceHDR/LuminanceHDR#227]
I'm using LuminanceHDR via the Manjaro Linux repos.

I love the idea of being able to **batch** tone map a series of HDR images, as I would like to perform some photogrammetry experiments, and to have to create them one by one would be painful.

However, the docs do not appear to contain the answer on how to perform this task.
https://luminancehdr.readthedocs.io/en/latest/tone_mapping/batch/

Specifically:
How do I create these "Tone Mapping Settings" and/or if some already exist, where would they be located?

**Comment by fcomida** [comment]
@verbal007 load an image in LHDR, choose your tonemapping setting then in thel main tonemapping panrl on the left you can choose either to save yours tm setting in a text file or in the internal database. In Batch tonemapping you can load that file or choose your setting from the db

**Comment by verbal007** [comment]
I will give this a try.  Thank you @fcomida !

**Comment by verbal007** [comment]
@fcomida , I'm looking at the main panel and unfortunately am not able to see any options to save my Tonemapping settings (see screenshot)
![lhdr_tonemappingSettingsSave](https://user-images.githubusercontent.com/5015124/103796366-f4f4c680-4ffb-11eb-89b4-e902bb84c6d3.jpg)
I've also checked the dropdown menus and haven't found anything.
Am I looking at the correct menu?

Luminance HDR 2.6.0
on Manjaro Linux

**Comment by fcomida** [comment]
@verbal007  click on "Settings" just above "Update preview" button

**Comment by verbal007** [comment]
@fcomida Ah! Found it. And it works.
Tricky little hidden panel switch (and tool tips that are apparently not working with my theme)
![hiddenPanel_2021-01-06](https://user-images.githubusercontent.com/5015124/103806723-4dcb5b80-500a-11eb-8700-8bb58c16b5b0.gif)

Thank your help!
