### ISSUE TITLE
how to load canon cr3 files

### ISSUE THREAD

**Issue by charlesgerbra** [LuminanceHDR/LuminanceHDR#246]
When attempting to create new HDR image, I click + to load images and navigate to a directory containing CR3 and JPG files. The HDR creation wizard lists only the JPG files, not the CR3 files. I have selected "All formats". If I select "RAW", then it lists no files.

I have version 2.6.1.1, linux/fedora34, libraw 0.20.2. Luminance-hdr includes canon eos r in its list of supported cameras. Other software using libraw can load CR3 images, eg, imagemagick, geeqie. 

How can I load CR3 images?

Edit: Whether I click "New HDR image" or "Open HDR image", the CR3 files are not listed. I have tried selecting both "All HDR formats" and "RAW images."

**Comment by aentwist** [comment]
I found the same thing. I take it that CR3 files are not supported? Which would make this a feature request.

**Comment by aentwist** [comment]
I had a look last night and it seems like [LibRaw supports this](https://www.libraw.org/supported-cameras) easily (via my case, Canon EOS M50), so it is either a matter of enabling it or wiring it. It looks like using raw format simply creates intermediate TIFF images for you [[1](https://luminancehdr.readthedocs.io/en/latest/getting_started/introduction/#summary-of-features)], so exporting to 16-bit TIFF yourself and using those should be an equivalent workaround.

**Comment by clanmills** [comment]
Last year, I added support for CR3 (and other bmff files including .HEIC) to Exiv2 and Roman added support to LibRaw.  This effort was made on the request of **darktable**. 

I believe LuminanceHDR can take advantage of those efforts.  If you have the build skills you may be able to tackle this on your own.  If you don't have the build skills, you may wish to start a discussion on the forum at discuss.pixls.us to see if others can help you.
