### ISSUE TITLE
Crashes when importing images

### ISSUE THREAD

**Issue by trenkert** [LuminanceHDR/LuminanceHDR#28]
I get this error message:

```

Warning: Luminance value out of permissible range 
gsl: init_source.c:34: ERROR: matrix dimension n2 must be positive integer
Default GSL error handler invoked.
```

**Comment by fcomida** [comment]
Could you please be more specific? Luminance HDR version, OS used, input images format, steps to reproduce the error. Thank you.

**Comment by Taxonoman** [comment]
I just downloaded the program a few minutes ago. 2.4.0 As soon as I try to add images (clicking the + button), it crashes every time. I am using Windows 10 on a 64-bit system.

**Comment by Beep6581** [comment]
Missing info and old version, I'd close.
