### ISSUE TITLE
Error with boost-1.85.0

### ISSUE THREAD

**Issue by conraid** [LuminanceHDR/LuminanceHDR#283]
When I compile with boost-1.85.0 I get this error:

`/tmp/hdr/LuminanceHDR/src/Libpfs/manip/resize.hxx:153:42: error: ‘boost::numeric’ has not been declared
  153 |                                   boost::numeric::bounds<Type>::highest()));
      |                                          ^~~~~~~
/tmp/hdr/LuminanceHDR/src/Libpfs/manip/resize.hxx:153:62: error: expected primary-expression before ‘>’ token
  153 |                                   boost::numeric::bounds<Type>::highest()));
      |                                                              ^
/tmp/hdr/LuminanceHDR/src/Libpfs/manip/resize.hxx:153:65: error: ‘::highest’ has not been declared
  153 |                                   boost::numeric::bounds<Type>::highest()));
      |                                                                 ^~~~~~~
make[2]: *** [src/Libpfs/CMakeFiles/pfs.dir/build.make:216: src/Libpfs/CMakeFiles/pfs.dir/manip/resize.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1169: src/Libpfs/CMakeFiles/pfs.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

Both with the latest git version and with 1.6.1.1.

I'm on Slackware current 64bit

**Comment by conraid** [comment]
I solved it with this fix

```
# Fix for boost >= 1.85.0
sed -i \
  '/constants\/constants/i #include <boost/numeric/conversion/bounds.hpp>' \
  src/Libpfs/manip/resize.hxx
```

**Comment by conraid** [comment]
Of course, in addition to the patches found in the main distributions

**Comment by creideiki** [comment]
> I solved it with this fix

This works in Gentoo as well, and I've submitted it as a proposed local patch there: https://bugs.gentoo.org/932335

**Comment by conraid** [comment]
Work fine, thanks.

**Comment by conraid** [comment]
Work fine, thanks.
