### ISSUE TITLE
"Fixes for Qt 5.6" (new QtWebEngine dependency) commit breaks LuminanceHDR for Debian Linux and derivatives

### ISSUE THREAD

**Issue by mandree** [LuminanceHDR/LuminanceHDR#29]
Greetings,

Debian and Ubuntu do not package/ship Qt5WebEngine (intentionally, see https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1579265 comment #2), thus commit 2a9fb80708ce24ba2362ed52b6a003687dfe420f breaks LuminanceHDR for Debian and derived distributions (Ubuntu, Mint, possibly others).

Please reinstate support for Qt5WebKit. Also note that Ubuntu Linux 16.04 LTS ships with Qt 5.5, so if it's not too much effort, it would be much appreciated to retain support for Qt 5.5 for the time being.

Thanks.

**Comment by fcomida** [comment]
I think it can be done, no need for a more advanced web rendering engine in Luminance HDR.
I'll reverse the offending commit ASAP

**Comment by fcomida** [comment]
So qtwebkit has been dropped on Windows and qtwebengine is supported on fedora and maybe other distros. I guess you Ubuntu guys have to patch Luminance if you will for getting qtwebkit support (and every other package that switched to qtwebengine for that matter...)
Sorry we are not gonna change the code for solving someone else problem.

**Comment by mandree** [comment]
Yeah, screw users of major Linux distros that care about getting the licenses straight. Brilliant idea. Not.

**Comment by fcomida** [comment]
We aren't screwing anybody, qtwebengine is the way to go according to
qtproject itself, what about qupzilla or other major projects switching to
qtwebengine?
Fedora for instance cares a lot about FOSS licenses and it managed to make
a qtwebengine package, debian and derivatives shouldn't screw their users
IMHO.
Anyway patching Luminance HDR for getting back qtwebkit shouldn't be so
difficult, please feel free to ask for help and/or suggestions.

**Comment by mandree** [comment]
Sorry, I have only so many open source projects I contribute to.
