### ISSUE TITLE
LuminanceHDR can't open TIFF images processed with ImageMagick

### ISSUE THREAD

**Issue by fliker09** [LuminanceHDR/LuminanceHDR#30]
I have a RAW image which I convert using RawTherapee into a 16-bit TIFF image. LuminanceHDR is opening it totally fine. But if I take that image and do any kind of processing using ImageMagick, the image can't be opened by LuminanceHDR anymore. Actually the app is opening, but image is totally black, histogram is empty. Pfstools handles OK the processed image. Transfer of the EXIF info using exiftool doesn't help. Links:

https://filebin.net/1ykjvg2j9dchs36w/DW1A1800.rt.tif
https://filebin.net/1ykjvg2j9dchs36w/DW1A1800.im.tif

**Comment by fcomida** [comment]
It seems an issue building a cms transform based on chromaticity vaues provided in the image tiff tags. I'm currently investigating it, could you please provide the original tiffs?
Thank you for reporting it.

**Comment by fliker09** [comment]
I've already given the links to the tiff files. Or I misunderstand something?

**Comment by fcomida** [comment]
I mean the original tif files, the ones not touched by ImageMagick. Anyway
I think I fixed it, your files are correctly imported now, really noisy
though. Maybe you could upload the raw too, I'll do some more testing.

Il 21/Set/2016 09:53, "fliker09" <notifications@github.com> ha scritto:

**Comment by fliker09** [comment]
DW1A1800.rt.tif is the one not touched by ImageMagick (rt - RawTherapee; im - ImageMagick). Link to the RAW file:

https://filebin.net/uozn1oovwc1ziroa/DW1A1800.CR2

**Comment by fcomida** [comment]
Ok, I got it!!! Well as I said I fixed it. 
Even the raw image is noisy, our raw importer can mitigate the problem a little enabling "noise reduction" in preferences.
Are you on Linux? You can get the fix if you are able to compile luminance yourself.

**Comment by fliker09** [comment]
Yeah, the problem with noise is known... But that isn't important for now :) Yes, I am on Linux. Are there any daily PPA out there? I can compile, but I would prefer to avoid it :\

**Comment by fcomida** [comment]
PPA means Ubuntu, there's an issue with Debian and derivatives since they don't provide QtWebEngine. It should be trivial patching the sources for getting QtWebKit back though. You can try contacting Ubuntu packagers, just keep in mind it's a development version, not sure if they are willing to build an "unstable" package.

**Comment by fliker09** [comment]
Which is why I asked about PPA - no need to contact Ubuntu packagers :) You say about QtWebKit problem... Does it mean that compiling from source may be problematic?

**Comment by fcomida** [comment]
QtWebKit is deprecated and not available on Windows anymore, so we switched to QtWebEngine for the Help Browser. Problem is QtWebEngine being a pain in the neck for Linux packagers (it's based upon Chromium code base, lots of dependencies that need to be worked out). Fedora and Arch Linux are distros that I know managed to build QtWebEngine, Debian and hence Ubuntu don't provide such package and probably never will (based on what I read so far).

**Comment by fliker09** [comment]
So... How do I compile on Ubuntu? :\ Is there a way to disable Help Browser (I don't need it for sure)?

**Comment by fliker09** [comment]
Thank you very much! luminance-hdr worked out-of-the-box, luminance-hdr-cli asked for libboost-program-options1.58.0 (installed - all good). Will test it out today!

**Comment by fliker09** [comment]
Tested it out... 2.4.0 is working nice, but gives artifacts (look at leaves). 2.4.1-SNAPSHOT gives very noisy image (and unsaturated), but no more artifacts. Links:

https://filebin.net/djbgiaxobtyoi3vh/luminance-hdr-cli-noag-2.4.0.hdr
https://filebin.net/djbgiaxobtyoi3vh/luminance-hdr-cli-noag-2.4.1.hdr

**Comment by fliker09** [comment]
Any news? Tried with other spheres, JPG and 16-bit TIFF - the same result, very high level of noise.

**Comment by fcomida** [comment]
I'll review the latest changes we made soon. I have a question not related
to the noise: what DE are you using? Any problem with program icons? It
should now use "system icons" when available regardeless icon theme used.

Il 28/Set/2016 15:20, "fliker09" <notifications@github.com> ha scritto:

**Comment by fliker09** [comment]
I am using Kubuntu 16.04, so it is KDE. Icons looks fine, none of them are missing as far as I can see.

**Comment by fcomida** [comment]
Yeah it's fine with KDE. I have a VM with elementary, had to set DESKTOP_SESSION to gnome, we'll see...Thanks
Il 28/Set/2016 17:07, fliker09 <notifications@github.com> ha scritto:I am using Kubuntu 16.04, so it is KDE. Icons looks fine, none of them are missing as far as I can see.

**Comment by Beep6581** [comment]
@fliker09 try again using git. Compilation is easy, instructions here https://discuss.pixls.us/t/compiling-luminance-hdr-in-linux/730

**Comment by shrx** [comment]
I have this problem with Luminance HDR 2.5.1 on OS X 10.10.5. I can provide a sample tiff file if needed.

**Comment by clanmills** [comment]
@shrx  Can you provide your file please?  I support building LHDR on MacOS-X (along with @HIRAM).  I've been asked to build LHDR 2.5.2 and will do that next week when I get home from vacation.

**Comment by shrx** [comment]
I tested it on linux too and it's the same.
Original file is a png: ![m42_10ms](https://user-images.githubusercontent.com/810337/32240346-69101bd8-be6d-11e7-8be4-f0bfdb1466d9.png)
Converted to tiff with imagemagick: [m42_10ms.tiff.zip](https://github.com/LuminanceHDR/LuminanceHDR/files/1431779/m42_10ms.tiff.zip)

**Comment by Beep6581** [comment]
541fdd84
```
"LoadFile: Cannot load /tmp/m42_10ms.tiff: TiffReader: unsupported photometric type"
```

```
-TIFF-IFD0:PhotometricInterpretation=BlackIsZero
```

**Comment by shrx** [comment]
@Beep6581 are you saying that this EXIF tag is missing from the tiff and I should add it manually?

**Comment by fcomida** [comment]
@shrx we don't support grayscale images. Convert it to RGB before exporting
it to TIFF.

**Comment by Beep6581** [comment]
@shrx no, what @fcomida said.
```
convert m42_10ms.tiff -type TrueColor m42_10ms_col.tif
```
