### ISSUE TITLE
Boolean CLI switch for Fattall "new" does not work.

### ISSUE THREAD

**Issue by tonurics** [LuminanceHDR/LuminanceHDR#32]
I've not been able to disable the new "Version 2.3.0" mode for Fattall via the command line.

I've tried the following combinations to no effect:
*) --tmoptions new=false
*) --tmoptions new=0
*) --tmoptions alpha=1:beta=0.9:color=1:noise=0:new=false
*) --tmoptions alpha=1:beta=0.9:color=1:noise=0:new=0

**Comment by fcomida** [comment]
Fixed in git. Use "--tmoFatNew false"

Thank you for reporting it.

**Comment by tonurics** [comment]
Thanks for the quick reply!

For clarification would the correct format of tmoptions be: 
--tmoptions alpha=1:beta=0.9:color=1:noise=0:new=false
[Assuming I wanted to set additional options.]

That's how I would read it from the man page, but I couldn't find any examples of the switches in use. Which left me testing various combinations of format strings in a hope of finding the correct one. 

For comparison, I'm setting the ev switch using:
--ev "0,2,-2,4,-4,6,-6"
[The extra quotes appear to be required.]

**Comment by fcomida** [comment]
I was referring to version 2.4.1 where we changed CLI parameter specification interface.
