### ISSUE TITLE
LDR images are saved with invalid embedded color profiles.

### ISSUE THREAD

**Issue by tonurics** [LuminanceHDR/LuminanceHDR#34]
When I save tonemapped images from LuminanceHDR CLI, the resulting files always produce an embedded color profile error in GIMP. Forcing me to convert it to GIMP's built-in sRGB profile. GIMP reports the erroneous profile as: "(invalid UTF-8 string)". I've tested TIFF, PNG, and JPG output formats they all produce same error.

Additional Information:
My input files are 12bit images [CR2 -> PPM -> TIFF] stored in 16bit TIFF, which are used to create a EXR [by LuminanceHDR CLI] in an earlier step. They themselves do not cause problems when opened in GIMP.

**Comment by fcomida** [comment]
I remember this error, it's a Gimp issue. What version of Gimp are you using?
I cannot reproduce the error tonemapping with 2.4.0 and 2.4.1 and opening the images with Gimp 2.8.18 and Gimp 2.9.4
In my system I have lcms2-2.8-2 linked by Gimp and Luminance HDR, it could be an issue with an older version of that library.

**Comment by tonurics** [comment]
My system details are:

gimp 2.8.18-1
lcms2 2.8-1
luminancehdr 2.4.0-8
[Arch Linux 64bit]
