### ISSUE TITLE
Exposure not auto-detected

### ISSUE THREAD

**Issue by vn971** [LuminanceHDR/LuminanceHDR#35]
Exposure is not auto-detected for some photos.
The photos I test are taken by OpenCamera-1.35 (on Android, installed from F-Droid).
According to GIMP-2.8.18, the photos do have an exposure value. GIMP says the Exif version is 2.2, the exposure itself is written in GIMP as "ExposureTime: 1/133s".

Any thoughts? Or maybe I'm doing something strange?

**Comment by fcomida** [comment]
Hello, 

can you please tell us which version, OS and picture format? Thank you.⁣

Inviato da BlueMail ​

Il giorno 2 Dic 2016 17:21, alle ore 17:21, Vasya Novikov <notifications@github.com> ha scritto:

**Comment by vn971** [comment]
Hi, thank you for your answer,

I'm Using ArchLinux, LiminanceHDR version 2.4.0-8. The picture format is
jpg.

**Comment by fcomida** [comment]
I'll investigate this issue. Since you are on Linux could you compile current developement version? It has new operators, autolevels and more. It shouldn't be difficult, we can help you through. Let me know.

Inviato da BlueMail ​

Il giorno 2 Dic 2016 17:53, alle ore 17:53, Vasya Novikov <notifications@github.com> ha scritto:

**Comment by vn971** [comment]
@fcomida if that could help, I will. Should I compile and test the dev version on the photos in question?

**Comment by vn971** [comment]
@fcomida UPD: sure, presuming that could help, I will.

**Comment by fcomida** [comment]
And if it works you'll⁣ have all new stuff and bugfixes. For us it's even easier to fix your issue, assuming it's still there. We hope to release the new version soon, new testers are very much welcomed.

Inviato da BlueMail ​

Il giorno 2 Dic 2016 18:09, alle ore 18:09, Vasya Novikov <notifications@github.com> ha scritto:

**Comment by vn971** [comment]
ArchLinux is tricky, compiling packages from source is so easy/mainstreamed that you are almost obliged to do it.:D
OK, I've done it now and can confirm the issue is **solved** in the newest version of LuminanceHDR.

Also, the "Qt>=5.3.2" patch is no longer needed ( https://git.archlinux.org/svntogit/community.git/tree/trunk/qt5_printsupport.diff?h=packages/luminancehdr ). Everything compiles without it.

Thank you very much for the help!

**Comment by vn971** [comment]
BTW, the documentation link seems to be broken, from http://qtpfsgui.sourceforge.net/?page_id=13
to https://sourceforge.net/projects/qtpfsgui.wiki/

**Comment by fcomida** [comment]
Cool, please test it and let us know. Documentation is outdated and
incomplete :(
