### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by siwica** [LuminanceHDR/LuminanceHDR#38]
I am trying to get familiar with Luminance HDR, but I am unable to find any documentation. All links on http://qtpfsgui.sourceforge.net/?page_id=13 are broken and I don't find any other site that contains these information.

Is there only the built-in help available?

**Comment by fcomida** [comment]
There is, altough a bit outdated and incomplete. You can reach it from
Help->Contents... or just hitting F1.
There are also some tutorials out there: try this
http://www.dr-lex.be/info-stuff/luminancehdr.html
<https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.dr-lex.be%2Finfo-stuff%2Fluminancehdr.html&h=ATMEIFB_p1SyCR09Dm-G71YiPOXjpjs0wAJgPIR8Qj7QxxYrZUe5sH5vZkKR4xWC9Rk03UPiFiFdwyBkN46J4dUrAVeqU4zM_xXfZpEKLgi-7XwHDri2r4cxbuJhrts>
for
instance, and few video tutorials as well on youtube, search from them. You
can even ask specific questions on our Facebook Page or Flickr page (
https://www.facebook.com/luminancehdr/ and
https://www.flickr.com/groups/qtpfsgui/), our small but growing community
will do its best in helping you out.

Cheers,
Franco
