### ISSUE TITLE
Wrong tooltips in Preferences dialog

### ISSUE THREAD

**Issue by mikhirev** [LuminanceHDR/LuminanceHDR#4]
Hi!

In Preferences -> RAW Conversion -> White Balance dialog there are numerous settings not related to white balance. The last is Saturation that has a wrong tooltips. Saturation checkbox tooltip is "White point ..." and spinbox tooltip is "White point value ...".

**Comment by davideanastasia** [comment]
Hi, I'll try to fix this one. Do you have any suggestion on how would you lay them down?

**Comment by mikhirev** [comment]
Well, I would not change a layout, just rename the tab (to "Color correction" may be?) and "Method" label to "White Balance Method". And, of course, fix these confusing tooltips.
