### ISSUE TITLE
Artifacts in highlights

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#43]
The HDR files produced by Luminance HDR 2.5.0 are unusable because they have gray-black artifacts in the highlights. I reproduced this using various input files, both PEF and 16-bit TIFF formats, using both linear and sRGB gamma encoding, using all 6 HDR profiles in LHDR, and I confirm that saving the HDR to Radiance RGBE, OpenEXR or HDR TIFF includes the artifacts.

Sample input files: https://filebin.net/mqthbifo9lt60pzx
The link will expire in 2 months, please save the files.

![imgur-2017_04_19-14 21 54](https://cloud.githubusercontent.com/assets/5844619/25179771/93ab9f1c-250b-11e7-9c62-42e39292e9a5.png)

**Comment by fcomida** [comment]
Only "Weights=Plateau" doesn't clip highlights.
![image](https://cloud.githubusercontent.com/assets/11018726/25219059/65240f2e-25ad-11e7-8f3d-365d08ff8ce9.png)
I'll look into this.

**Comment by fcomida** [comment]
Allright, fixed!!!
![image](https://cloud.githubusercontent.com/assets/11018726/25245810/fff3ec88-2605-11e7-857d-c69f8c5eeea6.png)
Thanks a lot for having spotted this out.

**Comment by fcomida** [comment]
Wait, wait, fixed for triangular weights. Let's tackle the other cases now :-|

**Comment by fcomida** [comment]
This one is with "Gaussian Weights"
![image](https://cloud.githubusercontent.com/assets/11018726/25246896/72efad28-2609-11e7-869c-a0a06edf027e.png)
So far so good, thanks again.

**Comment by Beep6581** [comment]
@fcomida if you commit each fix and mention the issue number in the commit message, e.g.
"Fix for clipped highlights using Gaussian weights, #43"
then the commit will automatically appear here, making it very easy to connect the code with the discussion. A cool GitHub feature.
Thank you for the fixes!

**Comment by fcomida** [comment]
Yeah, it seems to work, cool....

**Comment by Beep6581** [comment]
- [ ] Profile 1: Debevec, triangular, linear
- [ ] Profile 1: 
- [ ] Profile 1: 
- [ ] Profile 1: 
- [ ] Profile 1:

**Comment by Beep6581** [comment]
There seems to be a regression, because now all profiles show a lot of noise in the shadows of the HDR file (before tone mapping) even though the source images are clean.

**Comment by fcomida** [comment]
You are right, I'm sistematically going through all of the cases, only srgb response is still problematic. I'm gonna push the work later on, you'll be notified here.

**Comment by Beep6581** [comment]
I am happy to confirm that all profiles including Robertson result in HDR files which have no artifacts in the highlights and no noise. Good work!

-  Profile 1: Debevec, triangular, linear
![imgur-2017_04_29-21 11 00](https://cloud.githubusercontent.com/assets/5844619/25558134/97d38394-2d20-11e7-9cb8-3a681fa7cea7.png)

-  Profile 2: Debevec, triangular, gamma
![imgur-2017_04_29-21 11 05](https://cloud.githubusercontent.com/assets/5844619/25558135/9bd3049c-2d20-11e7-8e67-dcda49305840.png)

-  Profile 3: Debevec, plateau, linear
![imgur-2017_04_29-21 11 11](https://cloud.githubusercontent.com/assets/5844619/25558138/9f6522b6-2d20-11e7-9024-a1c1ea11dd0e.png)

-  Profile 4: Debevec, plateau, gamma
![imgur-2017_04_29-21 11 15](https://cloud.githubusercontent.com/assets/5844619/25558140/a38a58e8-2d20-11e7-9d43-9a715295a145.png)

-  Profile 5: Debevec, gaussian, linear
![imgur-2017_04_29-21 11 21](https://cloud.githubusercontent.com/assets/5844619/25558147/ad0fa1ca-2d20-11e7-9757-941eac363a86.png)

-  Profile 6: Debevec, gaussian, gamma
![imgur-2017_04_29-21 11 26](https://cloud.githubusercontent.com/assets/5844619/25558149/b13449fe-2d20-11e7-8044-c52456957bc8.png)

-  Custom: Robertson, triangular, gamma
![imgur-2017_04_29-21 11 31](https://cloud.githubusercontent.com/assets/5844619/25558150/b49296c8-2d20-11e7-8f0a-b35f3246e425.png)

**Comment by premier23** [comment]
Luminance HDR 2.5.1 running on windows 10.
Artifacts appear in the highlights and on almost any image as horizontal lines all over the image.

**Comment by Beep6581** [comment]
@premier23 please open a new issue and include useful information - see http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Requirements_of_a_good_bug_report
