### ISSUE TITLE
Light areas irrecoverably clipped when tone mapping

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#44]
All tone mapping operators clip the highlights to such a degree that I'm better off not passing the images through LHDR at all, as a single input image shows more highlight detail and less noise than the combined output of 5 images in LHDR 2.5.0. The fact that this happens with all TMOs suggests that the problem lies in the code before them.

Sample input files: https://filebin.net/mqthbifo9lt60pzx
The link will expire in 2 months, please save the files.

The light areas are not clipped in the source images nor in the HDR image, they are only clipped when tone mapping:
![imgur-2017_04_19-14 21 54](https://cloud.githubusercontent.com/assets/5844619/25180033/b0a3e790-250c-11e7-88a8-554428ec3368.png)

![imgur-2017_04_19-14 32 20](https://cloud.githubusercontent.com/assets/5844619/25180112/0818bb2c-250d-11e7-8b8b-939f1182469d.png)

![imgur-2017_04_19-14 29 36](https://cloud.githubusercontent.com/assets/5844619/25180034/b0a4bf30-250c-11e7-87f8-bbd7ed6da375.png)

![imgur-2017_04_19-14 36 11](https://cloud.githubusercontent.com/assets/5844619/25180251/8d998362-250d-11e7-978d-ab46910a0a1e.png)

Not being able to compress the dynamic range of the scene so as to preserve highlight detail defeats the purpose of using (L)HDR.

**Comment by fcomida** [comment]
Disable "auto levels". The problem with clipped highlights in HDRs remains though, weights = plateau doesn't show the clipping and sometimes clipping doesn't affect tonemapped images. It must be fixed anyway.

**Comment by Beep6581** [comment]
> Disable "auto levels".

Ah! :P That was it. Tested using git head 1ec161f9 and it's all fine. Issue can be closed.
