### ISSUE TITLE
Minimum width of left panel too huge

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#45]
The left "Tonemap" panel's minimum width is huge, leaving no room for the preview on non-fullHD screens.

This screenshot shows the panel's minimal width:
![imgur-2017_04_19-14 49 10](https://cloud.githubusercontent.com/assets/5844619/25180740/72191024-250f-11e7-8447-f8ac76a5d86f.png)

LHDR 2.5.0.

**Comment by fcomida** [comment]
After a quick check it seems TMPanel has no minimum size. Let see whether I can get it shrinks even more...BTW what's your monitor resolution?

**Comment by Beep6581** [comment]
@fcomida thanks for looking into this. My current monitor (laptop) is 1920x1080 so it's not that much of a problem for me currently, though I would like to be able to have a larger preview area instead of a large panel.

**Comment by fcomida** [comment]
@Beep6581 I reduced panel width by 110px, not bad for a small monitor.

**Comment by Beep6581** [comment]
That's 110px better.

Reinhard '02's panel can be improved by moving the "Use scales" checkbox down:
![imgur-2019_01_07-22 12 11](https://user-images.githubusercontent.com/5844619/50793743-6bee0c00-12c9-11e9-8888-fdc07cda2a90.png)

**Comment by fcomida** [comment]
@Beep6581 It could making it looking better maybe, the problem is that everything must shrink at the same time, visible and invisible widget. The minimum with is now dictated by the minimum width of "update preview" button, "Update current LDR" and "Auto Levels" check boxes.
