### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by joegiampaoli** [LuminanceHDR/LuminanceHDR#46]
Hello

I have been having a bit of trouble compiling 2.5.0 on Debian Jessie 64 bit

I already have installed a newer version of QT (QT 5.7.0) and put it in my environment. I have also updated cmake to latest version (3.8.0) and have pfstools 1.8.5 from Debian, I understand that 1.8 is minimum needed to compile HDRHTML support.

This is what I get at cmake step:

`joe@pc-joe:~/Desktop/111$ cmake /home/joe/Desktop/luminance-hdr-2.5.0
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++11 activated for GCC 4.9.2

-- GCC >= 4.3
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Performing Test HAS_BRANCH_PEDICTION
-- Performing Test HAS_BRANCH_PEDICTION - Success
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- Found LIBRAW: /usr/lib/x86_64-linux-gnu/libraw_r.so  
-- Found LibRAW (LIBRAW_INCLUDE_DIR = /usr/include)
-- Found LibRAW (LIBRAW_LIBRARIES = /usr/lib/x86_64-linux-gnu/libraw_r.so)
-- Found demosaicing pack GPL2
-- Found demosaicing pack GPL3
-- Found FFTW3F (FFTWF_INCLUDE_DIR = /usr/include)
-- Found FFTW3F (FFTWF_LIBRARIES = /usr/lib/x86_64-linux-gnu/libfftw3f.so;/usr/lib/x86_64-linux-gnu/libfftw3f_threads.so)
-- Found LCMS2: /usr/lib/x86_64-linux-gnu/liblcms2.so  
-- Found LCMS2 (LCMS2_LIBRARIES = /usr/lib/x86_64-linux-gnu/liblcms2.so)
-- Found LCMS2 (LCMS2_INCLUDE_DIR = /usr/include)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   program_options
--   thread
--   chrono
--   system
--   date_time
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for module 'exiv2'
--   Found exiv2, version 0.24
-- Found Exiv2: /usr/lib/x86_64-linux-gnu/libexiv2.so (Required is at least version "0.21") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.3") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libHalf.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libImath.so  
-- OpenEXR found
-- Found GNU Scientific Library (GSL_LIBRARY = /usr/lib/libgsl.so)
-- Found GNU Scientific Library: (GSL_CBLAS_LIBRARY = /usr/lib/libgslcblas.so)
-- Found GNU Scientific Library: (GSL_INCLUDE_DIR = /usr/include)
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found CFITSIO: /usr/lib/x86_64-linux-gnu/libcfitsio.so  
-- Installation of Luminance HDR 2.5.0 in /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joe/Desktop/111
`

And this is what I get at make:

`joe@pc-joe:~/Desktop/111$ make
Scanning dependencies of target hdrhtml-cli
[  0%] Building CXX object src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp: In member function ‘void hdrhtml::HDRHTMLSet::add_image(int, int, float*, float*, float*, float*, const char*, const char*, int, bool)’:
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: error: no matching function for call to ‘std::locale::locale(std::string&)’
   locale::global(locale(user_locale));
                                    ^
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: note: candidates are:
In file included from /usr/include/c++/4.9/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:32:
/usr/include/c++/4.9/bits/locale_classes.h:311:5: note: std::locale::locale(std::locale::_Impl*)
     locale(_Impl*) throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:311:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘std::locale::_Impl*’
/usr/include/c++/4.9/bits/locale_classes.h:178:7: note: template<class _Facet> std::locale::locale(const std::locale&, _Facet*)
       locale(const locale& __other, _Facet* __f);
       ^
/usr/include/c++/4.9/bits/locale_classes.h:178:7: note:   template argument deduction/substitution failed:
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: note:   cannot convert ‘user_locale’ (type ‘std::string {aka std::basic_string<char>}’) to type ‘const std::locale&’
   locale::global(locale(user_locale));
                                    ^
In file included from /usr/include/c++/4.9/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:32:
/usr/include/c++/4.9/bits/locale_classes.h:164:5: note: std::locale::locale(const std::locale&, const std::locale&, std::locale::category)
     locale(const locale& __base, const locale& __add, category __cat);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:164:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.9/bits/locale_classes.h:151:5: note: std::locale::locale(const std::locale&, const char*, std::locale::category)
     locale(const locale& __base, const char* __s, category __cat);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:151:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.9/bits/locale_classes.h:137:5: note: std::locale::locale(const char*)
     locale(const char* __s);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:137:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.9/bits/locale_classes.h:126:5: note: std::locale::locale(const std::locale&)
     locale(const locale& __other) throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:126:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::locale&’
/usr/include/c++/4.9/bits/locale_classes.h:117:5: note: std::locale::locale()
     locale() throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:117:5: note:   candidate expects 0 arguments, 1 provided
src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/build.make:62: recipe for target 'src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o' failed
make[2]: *** [src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o] Error 1
CMakeFiles/Makefile2:2247: recipe for target 'src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/all' failed
make[1]: *** [src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

Any ideas or tips?

Thank you...

**Comment by fcomida** [comment]
See issue #41

**Comment by joegiampaoli** [comment]
Thanks for your reply and support!

Line 383 in hdrhtml.cpp is an empty line, if I add:

locale::global(locale(user_locale.c_str()));

to that line I get: 

Scanning dependencies of target hdrhtml-cli
[  0%] Building CXX object src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:36: error: expected ‘)’ before ‘.’ token
   locale::global(locale(user_locale.c_str()));
                                    ^
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:36: error: expected ‘)’ before ‘.’ token
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:36: error: ISO C++ forbids declaration of ‘global’ with no type [-fpermissive]
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:36: error: cannot declare member function ‘std::locale::global’ within ‘hdrhtml::ReplacePattern’
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:25: error: expected ‘;’ at end of member declaration
   locale::global(locale(user_locale.c_str()));
                         ^
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:383:36: error: expected unqualified-id before ‘.’ token
   locale::global(locale(user_locale.c_str()));
                                    ^
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp: In member function ‘void hdrhtml::HDRHTMLSet::add_image(int, int, float*, float*, float*, float*, const char*, const char*, int, bool)’:
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: error: no matching function for call to ‘std::locale::locale(std::string&)’
   locale::global(locale(user_locale));
                                    ^
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: note: candidates are:
In file included from /usr/include/c++/4.9/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:32:
/usr/include/c++/4.9/bits/locale_classes.h:311:5: note: std::locale::locale(std::locale::_Impl*)
     locale(_Impl*) throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:311:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘std::locale::_Impl*’
/usr/include/c++/4.9/bits/locale_classes.h:178:7: note: template<class _Facet> std::locale::locale(const std::locale&, _Facet*)
       locale(const locale& __other, _Facet* __f);
       ^
/usr/include/c++/4.9/bits/locale_classes.h:178:7: note:   template argument deduction/substitution failed:
/home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:838:36: note:   cannot convert ‘user_locale’ (type ‘std::string {aka std::basic_string<char>}’) to type ‘const std::locale&’
   locale::global(locale(user_locale));
                                    ^
In file included from /usr/include/c++/4.9/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /home/joe/Desktop/luminance-hdr-2.5.0/src/HdrHTML/hdrhtml.cpp:32:
/usr/include/c++/4.9/bits/locale_classes.h:164:5: note: std::locale::locale(const std::locale&, const std::locale&, std::locale::category)
     locale(const locale& __base, const locale& __add, category __cat);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:164:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.9/bits/locale_classes.h:151:5: note: std::locale::locale(const std::locale&, const char*, std::locale::category)
     locale(const locale& __base, const char* __s, category __cat);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:151:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.9/bits/locale_classes.h:137:5: note: std::locale::locale(const char*)
     locale(const char* __s);
     ^
/usr/include/c++/4.9/bits/locale_classes.h:137:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.9/bits/locale_classes.h:126:5: note: std::locale::locale(const std::locale&)
     locale(const locale& __other) throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:126:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::locale&’
/usr/include/c++/4.9/bits/locale_classes.h:117:5: note: std::locale::locale()
     locale() throw();
     ^
/usr/include/c++/4.9/bits/locale_classes.h:117:5: note:   candidate expects 0 arguments, 1 provided
src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/build.make:62: recipe for target 'src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o' failed
make[2]: *** [src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/hdrhtml.cpp.o] Error 1
CMakeFiles/Makefile2:2247: recipe for target 'src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/all' failed
make[1]: *** [src/HdrHTML/CMakeFiles/hdrhtml-cli.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2


Thanks, I appreciate your help!

**Comment by fcomida** [comment]
It's in fact line 838, what a typo....

**Comment by joegiampaoli** [comment]
Ah! What a typo indeed!

That worked like a charm! All good and running like a sweetheart...

Really appreciate your help...
