### ISSUE TITLE
Covert Docs to sphinx and host on RTD

### ISSUE THREAD

**Issue by Blendify** [LuminanceHDR/LuminanceHDR#47]
Hi, I am purposing that the current docs get converted to http://www.sphinx-doc.org/en/stable/ and written in RST. The docs can then be hosted on https://readthedocs.org/. I am writing this to discuss the topic and will open a PR later.

**Comment by Blendify** [comment]
A preview can be found at http://luminancehdr.readthedocs.io/en/latest/ and source is at https://github.com/Blendify/LuminanceHDR/tree/docs-sphinx

**Comment by Blendify** [comment]
@fcomida What do you think about this?

**Comment by fcomida** [comment]
It sounds like a good idea, the only problem is that our documentation is a bit outdated and incomplete (euphemism....), we need to find a way to expand/improve it. Does this system allow users contribution to the documentation (wikipedia style)? I can see an **Edit on GitHub** link. How is this supposed to work?

**Comment by Blendify** [comment]
It is not wikipedia style but people can hit the edit on github button and submit a PR for this repository.
