### ISSUE TITLE
Bloated HTML markup in strings

### ISSUE THREAD

**Issue by mikhirev** [LuminanceHDR/LuminanceHDR#57]
Hi!

There are many strings with terrible auto-generated HTML markup which are very hard to translate. One example:

~~~
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Sans Serif'; font-size:13pt; font-weight:400; font-style:normal;">
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600; color:#0078dc;">Luminance HDR</span></p></body></html>
~~~

There are doctype definition, embedded CSS, styles defined for `body`,  `p` and `span` elements. This string is half a kilobyte, but all its content is `Luminance HDR`. Translators need to "parse" all this crap by eyes just to understand that there's nothing to translate. I understand that such strings are auto-generated by IDE, but I believe there must be a way to reduce the markup. In many cases such "rich text" can be simply replaced with plain text.

**Comment by fcomida** [comment]
The translation tools should actually parse the content and present translators with only what's worth translating....All that crap for having **Luminance HDR** string looking good in **ligth** and **dark** themes....so plain text won't do. I know it's frustrating but there are only a couple or something of such formatted strings. Transiflex does color "html" suff in light blue and "translatable strings" in black but when you copy everything in the translation area it becomes all black...what can I do? Thanks for your contribution anyway.

**Comment by mikhirev** [comment]
> there are only a couple or something of such formatted strings.

Couple dozens you mean? Search for `!DOCTYPE` on Transifex finds 25 strings.

Well, if sometimes HTML is really required, it still does not need to be so bloated. There's no need for doctype declaration, such a huge number of nested elements and styles defined in three(!) different places. There are also strings with several paragraphs, each containing span inside, and each `<p>` and `<span>` element has its own style definition, alhough they are the same for all elements. Syntax highlighting does not help much when real content is only 5-10% of the text.

**Comment by fcomida** [comment]
As I said, what can I do about it? 25 over 1154 is roughly 2% and only 2 are big chunks of text, you should turn your complains toward the Qt folks, I can't break the interface since that crap is created automatically.

**Comment by danielkaneider** [comment]
Unfortunately Qt doesn't make it always easy to translate texts. UI Designer has just a flag to mark a specific string as _translatable_ or not. This applies either to all of it (including Html markup), or none. This Html markup is limited to just a few places (about dialog for example), we choose to go with the first option. As a translator you have the option to leave such strings untranslated. Since this doesn't affect a lot of dialogs, this should be ok for the user.
@mikhirev Thanks for your translation efforts anyway.
