### ISSUE TITLE
Auto Levels threshold has no effect

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#58]
Using latest git e7fd376f15f1110536abaf19b9782a20256e89b2 the threshold selector for auto levels has no effect on the main preview, only on the thumbnails. I'm filing the bug report only because the changelog for 2.5.1 mentions it.

**Comment by fcomida** [comment]
It actually works, you must hit `return` for the changes to apply....no very intuitive isn't it?

**Comment by fcomida** [comment]
Ops, Qt differentiates among `return` key and `enter` key. I must fix this...

**Comment by Beep6581** [comment]
I tried a few days ago and it worked when I hit enter, but as you said, that is not very intuitive. As you closed the issue, does that mean that now the user does not have to hit enter? i.e. is dragging the slider enough?

**Comment by fcomida** [comment]
I'll have a look whether I can send a signal when the widget goes out of focus for notifying the threshold has been set.

**Comment by fcomida** [comment]
OT: are you using a chat application for your project? Slack, HipChat?

**Comment by Beep6581** [comment]
Just IRC. Though "just" is not the right word ;)

**Comment by fcomida** [comment]
There's also Gitter among the ones integrated with GitHub, we should consider using one of them...

**Comment by Beep6581** [comment]
The thing about IRC is that people can just drop by without needing to sign up, sign in or install anything (assuming they already use IRC, which is a likely assumption as freenode is full of users and developers of all sorts of open-source software, from games to the folks at pixls.us). That's the same advantage GitHub has over other platforms, which require that you register or sign up specially for them just to report a bug. So for me, IRC is ideal, and for the same reason I don't see myself using anything else.
