### ISSUE TITLE
Default EV in HDR Creation Wizard when unknown

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#59]
This is a small thing which annoys me in a disproportionately big way. When loading a set of images which have no exposure metadata, the EV slider is at 0 but the column shows "Unknown". Let's say I load 5 images. I set the first one to -4, click on the second and set it to -2, click on the third and... I have to set it to something other than 0 only to be able to set it to 0.

I see three ways of improving this:
1. My preferred choice is for there to be a button which automatically sets EV spacing for all images, default is 2EV apart.
2. The default value could be 0, not "unknown".
3. Clicking on an "Unknown" image could automatically set it to the value of the slider (which by defaut is 0).

**Comment by fcomida** [comment]
Agreed, and a choice for not showing the warning dialog again

**Comment by fcomida** [comment]
@Beep6581 please checkout `hdrwizard` branch

**Comment by Beep6581** [comment]
Works well!

**Comment by fcomida** [comment]
It annoys me too, one of those easy things you promise yourself to fix and always forget to actually do. Queued for 2.5.2...

**Comment by Beep6581** [comment]
Curious why it's not merged into master yet.

**Comment by fcomida** [comment]
Too late for 2.5.1

**Comment by fcomida** [comment]
@Beep6581 BTW development is carried on  `development branch` or any other branch from now on. On `master` only bugfixes.

**Comment by Beep6581** [comment]
Thanks @fcomida !
