### ISSUE TITLE
Local storage folders messy

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#60]
Luminance HDR stores several files on a user's system:
* `$HOME/.config/Luminance HDR Development Team/Luminance HDR.conf`
* `$HOME/.LuminanceHDR/saved_parameters.db`
* `$HOME/.config/Luminance HDRrc`

All of those are messy at best, wrong at worst.

Please patch LHDR to store them in `$HOME/.config/luminancehdr` (no spaces, no "Development Team" which makes no sense for a folder name, and preferably though not necessarily no capitalization).

**Comment by fcomida** [comment]
First of all: who cares? Path name under `.config` is created by Qt based on application name and organization name after calling `QCoreApplication::setApplicationName(..)` and `QCoreApplication::setOrganizationName(...)`, `$HOME/.config/Luminance HDRrc`  is KDE stuff (using application name as set by Qt), `$HOME/.LuminanceHDR/saved_parameters.db` should follow the conventions used above but again, who cares? I have all sort of mess under my `~/.config`, every app I installed seems to follow different conventions there (I even have `~/.config/Unknown Organization/` for a couple of Qt applications).
`

**Comment by Beep6581** [comment]
> who cares?

I do, I appreciate when a program's developers take an extra moment to keep config, cache and data files organized. It makes it easier to do cleanups and backups. There are standards, and things go more smoothly when standards are obeyed. 

> Path name under .config is created by Qt based on application name and organization name

The FreeDesktop standard has this to say about the name:
https://www.freedesktop.org/software/systemd/man/file-hierarchy.html

> ~/.config/package | User-specific configuration and state for the package. It is required to default to safe fallbacks if this configuration is missing.

The keyword is "package". It does not explicitly say that an organization name should not be used, but when I take a look at the contents of my ~/.config folder I see that LHDR is the only program which suffixes an organization name to the folder name. Doesn't that tell you that this is probably not the way to go?

> $HOME/.config/Luminance HDRrc is KDE stuff

True, but also the least significant of all points. The only reason I mentioned it was because I see some programs have their *rc files within subfolders. I don't know how they do that, but it seems its possible. But again, not significant.

> I have all sort of mess under my ~/.config, every app I installed seems to follow different conventions there

That is unfortunate, but also not a reason for LHDR disregard it. I have filed reports with various programs/companies, including some closed-source ones, to help clean up their act, and I'm happy to see that it paid off every time.

The main point of this whole issue is `$HOME/.LuminanceHDR/saved_parameters.db`, please move it to `$HOME/.config/package`.

**Comment by fcomida** [comment]
I guess I have to do it with some `#ifdef`. Not sure but organization is important on Mac and maybe Windows too. We just set those names and Qt do the rest. Settings are handled by Qt in a platform agnostic way. What do you (and freedesktop) mean by `package`? The name chosen by the X Linux distribution? Again every distro name a package differently most of the time, so yes lack of standards has been a plague for linux since the very beginning. 
In fedora the package is named `luminance-hdr`, is this correct? Should have it been called `Luminance HDR` since this is the upstream application name?
I will move `$HOME/.LuminanceHDR/saved_parameters.db` with maybe some code to move the old database there (if existing) after an update.

**Comment by Beep6581** [comment]
> What do you (and freedesktop) mean by `package`? 

That's not clear, but all the programs I have installed use just the program name, and most make it lowercase without spaces, periods or other special characters.

> Again every distro name a package differently

The config folder names come from the packages themselves, not from the distro (or package manager). I'm not experienced with Qt code, but in the Gtk+ program I contribute to we define the folder name manually.

> In fedora the package is named luminance-hdr, is this correct? Should have it been called Luminance HDR since this is the upstream application name?

I don't know about Fedora. Gentoo tends to make rigorous checks, because all packages in Gentoo are compiled by the user and they must all play along nicely, so I tend to take what they (Gentoo) do into account, and they don't rename the LHDR executable:
2.4.0: https://gitweb.gentoo.org/repo/gentoo.git/tree/media-gfx/luminance-hdr/luminance-hdr-2.4.0.ebuild
2.5.0: https://github.com/vivo75/vivovl/blob/master/media-gfx/luminance-hdr/luminance-hdr-2.5.0.ebuild

When I manually compile LHDR from git the executable is called `luminance-hdr` and that's perfect.

**Comment by fcomida** [comment]
Well `package name` is then `program name` on linux. I'll have to use `#ifdef` to set QSettings accordingly on linux and then save/move `saved_parameters` under `$HOME/.config/luminance-hdr`.

**Comment by fcomida** [comment]
@Beep6581 no sure whether "saved_parameter.db" should go to "$HOME/.config/luminance-hdr" or to "$HOME/.local/share/applications/luminance-hdr".

**Comment by Beep6581** [comment]
`~/.local/share` is for "Resources shared between multiple packages, such as fonts or artwork".
LHDR does not share anything with other programs, so everything which doesn't go to `~/.cache` should go to `~/.config`.
