### ISSUE TITLE
[request] Luminance 2.5.1 windows portable version

### ISSUE THREAD

**Issue by lustek** [LuminanceHDR/LuminanceHDR#65]
The last portable version of Luminance is 2.4.0. Can you create one also for 2.5.1?

**Comment by fcomida** [comment]
2.5.1 is actually portable, there's a check box in the installer for activating **Portable Mode** and a checkbox on **Preferences Dialog/Interface**

**Comment by lustek** [comment]
Unfortunately I can't execute the installer, as I don't have admin privileges on my computer. The standalone 2.4 portable version works fine on this computer

**Comment by fcomida** [comment]
@lustek I've uploaded a zipped archive on sourceforge. Just unzip it on your pendrive and set **Portable Mode** in **Preferences**
[Luminance-HDR-x64-v2.5.1.zip](https://sourceforge.net/projects/qtpfsgui/files/luminance/2.5.1/Luminance-HDR-x64-v2.5.1.zip/download)

**Comment by lustek** [comment]
thanks for your super fast reaction!
