### ISSUE TITLE
No Success with Command-Line on Mac OS 10.11

### ISSUE THREAD

**Issue by LarryM2** [LuminanceHDR/LuminanceHDR#72]
I am trying to create an HDR image with four 16-bit color TIFFs using LuminanceHDR's command-line interface (ver 2.5.1) on Mac OS 10.11, but no matter what I enter on the command-line, there are error messages.  If I enter:

> ./luminance-hdr-cli" --ev 0, .69, 1.38, 2.34 -o ~/Desktop/HDRTest2.tif  —-ldrTiff 16b ~/TestImages/LDRImage16-1.tif ~/TestImages/LDRImage16-2.tif ~/TestImages/LDRImage16-3.tif ~/TestImages/LDRImage16-4.tif

the error is: "Cannot convert  to a float"

If I remove the spaces between the -ev values, the error is "Error: The number of EV values specified is different from the number of input files."

If I leave out the -ev values altogether, the output is:

> "HdrCreationManager::loadFiles(): Checking —-ldrTiff"
"HdrCreationManager::loadFiles(): Schedule loading for —-ldrTiff"
"HdrCreationManager::loadFiles(): Checking 16b"
"HdrCreationManager::loadFiles(): Schedule loading for 16b"
"HdrCreationManager::loadFiles(): Checking /Users/admin/TestImages/LDRImage16-1.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /Users/admin/TestImages/LDRImage16-1.tif"
"HdrCreationManager::loadFiles(): Checking /Users/admin/TestImages/LDRImage16-2.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /Users/admin/TestImages/LDRImage16-2.tif"
"HdrCreationManager::loadFiles(): Checking /Users/admin/TestImages/LDRImage16-3.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /Users/admin/TestImages/LDRImage16-3.tif"
"HdrCreationManager::loadFiles(): Checking /Users/admin/TestImages/LDRImage16-4.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /Users/admin/TestImages/LDRImage16-4.tif"
"LoadFile: Loading data for 16b"
"LoadFile: Loading data for /Users/admin/TestImages/LDRImage16-1.tif"
"LoadFile: Loading data for —-ldrTiff"
"LoadFile: Loading data for /Users/admin/TestImages/LDRImage16-2.tif"
"LoadFile: Loading data for /Users/admin/TestImages/LDRImage16-3.tif"
"LoadFile: Loading data for /Users/admin/TestImages/LDRImage16-4.tif"
"LoadFile: Cannot load —-ldrTiff: Cannot find the correct handler for —-ldrTiff"
"LoadFile: Cannot load 16b: Cannot find the correct handler for 16b"
TIFFReadDirectory: TIFFReadDirectory: TIFFReadDirectory: TIFFReadDirectory: Warning, Warning, Warning, Warning, Unknown field with tag 37553 (0x92b1) encounteredUnknown field with tag 37553 (0x92b1) encounteredUnknown field with tag 37553 (0x92b1) encounteredUnknown field with tag 37553 (0x92b1) encountered.
.
.
.
TIFFReadDirectory: TIFFReadDirectory: TIFFReadDirectory: Warning, TIFFReadDirectory: Warning, Warning, Unknown field with tag 37554 (0x92b2) encounteredWarning, Unknown field with tag 37554 (0x92b2) encounteredUnknown field with tag 37554 (0x92b2) encountered.
Unknown field with tag 37554 (0x92b2) encountered.
.
.
"LoadFile: Average Luminance for /Users/admin/TestImages/LDRImage16-2.tif is -1"
"LoadFile: Average Luminance for /Users/admin/TestImages/LDRImage16-4.tif is -1"
"LoadFile: Average Luminance for /Users/admin/TestImages/LDRImage16-1.tif is -1"
"LoadFile: Average Luminance for /Users/admin/TestImages/LDRImage16-3.tif is -1"
HdrCreationManager::loadFilesDone(): Data loaded ... move to internal structure!
Failed loading images

The unknown tags are our proprietary TIFF tags.

Is there any way to create an HDR from four 16-bit TIFFs from the command-line.  I am able to create one with these same four files with the GUI app.

Thank You

Larry

**Comment by fcomida** [comment]
You must remove all spaces between EV values. Check the 1st "minus" in `--ldrTiff 16`, it's wrong (it's not a minus char, if you just "copied and pasted" here from your commandline). If you fix that it should work, the error message you got is indeed misleading though...

**Comment by LarryM2** [comment]
I had tried the command-line both with and without the spaces in the EV values, but it appears that the '-' char in the "ldrTiff" argument was the problem.  I was able to create an image this time.

Thank You

Larry
