### ISSUE TITLE
Unable to open Tiff File

### ISSUE THREAD

**Issue by bcoppernoll** [LuminanceHDR/LuminanceHDR#73]
When I try to open a Tiff file saved with GIMP I get the following error:

HdrCreationManager::loadFilesDone(): Error loading a file.

I am on Linux Mint 18.1, using Luminance HDR 2.5.1 from the repo.

I have attached the Tiff file.

Please let me know if there is any additional information needed.

[Totality-125-Stacked-test.tif.zip](https://github.com/LuminanceHDR/LuminanceHDR/files/1252517/Totality-125-Stacked-test.tif.zip)

**Comment by fcomida** [comment]
@bcoppernoll Reading TIFF tags with `tiffinfo` I get: **Photometric Interpretation: min-is-black** which is not supported by LHDR (a bi-level black and white image where 0 is black according to TIFF specs).

**Comment by bcoppernoll** [comment]
@fcomida Thanks, I was able to find the issue with your help.  I was using Siril to pre-process the images, did not catch it was outputting a black and white image.  Changed it to output color and that solved the problem.
