### ISSUE TITLE
Possible speedup for tonemapping operators

### ISSUE THREAD

**Issue by heckflosse** [LuminanceHDR/LuminanceHDR#76]
When using fattal02 a lot of processing time is spent in [findMaxMinPercentile()](https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/fattal02/tmo_fattal02.cpp#L288)

Recently @agriggio ported the fattal02 code to RawTherapee and I made a serious speedup (about 100 times faster in my tests) for [findMaxMinPercentile()](https://github.com/Beep6581/RawTherapee/blob/hdr_tonemap_fattal/rtengine/tmo_fattal02.cc#L403)

Feel free to use it in your code as well.

Ingo

**Comment by fcomida** [comment]
Hi Ingo,

impressive, just quickly dropped your code and recompiled. Fattal is 120%
faster now...
Thank you for sharing it.

Franco

**Comment by heckflosse** [comment]
Hi fcomida,

maybe also worth to have a look at the [log-loop](https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/fattal02/tmo_fattal02.cpp#L343) and [exp-loop](https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/fattal02/tmo_fattal02.cpp#L464).

These are both very expensive but can get nice speedups by using sleef functions, SSE2 and omp.
Here's the code for the equivalent [log](https://github.com/Beep6581/RawTherapee/blob/hdr_tonemap_fattal/rtengine/tmo_fattal02.cc#L530) and [exp](https://github.com/Beep6581/RawTherapee/blob/hdr_tonemap_fattal/rtengine/tmo_fattal02.cc#L733) loops in RawTherapee fattal code.

With my test file the log-loop took 10.2 seconds with the simple code and now takes 0.19 seconds. 
The exp-loop took 5.4 seconds with the simple code and now also takes 0.19 seconds.

But you need [sleef](https://github.com/Beep6581/RawTherapee/blob/hdr_tonemap_fattal/rtengine/sleef.c) to use the faster scalar xexpf and xlogf functions and [sleefsseavx](https://github.com/Beep6581/RawTherapee/blob/hdr_tonemap_fattal/rtengine/sleefsseavx.c) to use the vectorized functions.

**Comment by fcomida** [comment]
Yeah I just changed findMinMaxPercentile (or whatever).
Do you guys have plans for OpenCL (or maybe your code already supports it)?
I experimented a bit with boost::compute and have the simplest tmos running
on GPU (drago and reinhard05) with ~ 10x speed gain so far.

**Comment by heckflosse** [comment]
We don't support OpenCl and there are no plans for supporting it in RT (not enough manpower to do that atm). We try to get speed by using omp, SSE and optimizing algorithms.

We got a lot of speedups by using sleef btw. And we use since a while (since 2014 iirc) without issues

**Comment by fcomida** [comment]
Talking about manpower? :D
Actually only Davide did some good work with tonemapping algorithms (see
fattal...).
I'm the one, in my very limited spare time, trying to prevent the whole
house of card from collapsing, gosh!!! Fortunately most users don't see
what's under the hood :O

**Comment by heckflosse** [comment]
My time does not permit to contribute to Luminance HDR except the way I do currently by reporting the speedups we made for fattal to you. I hope this is welcome.

Ingo

**Comment by fcomida** [comment]
very much welcome of course. I was just stating how things are in the LHDR
camp right now. Actually no manpower at all, I'm trying to ship something
usable acknowledging that a lot of work must be done and cannot be done.
Still like poking around the code though.
Thanks again.

**Comment by heckflosse** [comment]
Hi Franco,

these loops deserve omp usage too:

https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/fattal02/tmo_fattal02.cpp#L400

https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/fattal02/tmo_fattal02.cpp#L429

Ingo

**Comment by fcomida** [comment]
Hi Ingo,

i'm applying your technique to others operators, I have drago 3x faster.
Great stuff....

**Comment by heckflosse** [comment]
@fcomida Franco, about [drago](https://github.com/LuminanceHDR/LuminanceHDR/blob/master/src/TonemappingOperators/drago03/tmo_drago03.cpp#L59):

```
    for (int i = 0; i < size; i++) {
        avLum += log(Y[i] + 1e-4);
...
```
Maybe you can use the fact that mathematically:
```
log(x1) + log(x2) + ... + log(xn) = log(x1 * x2 * ... * xn)
```
to speedup this loop even further.

Though it's not numerical equivalent and may need to use double precision for the multiplication.
It would mean only one log and n multiplications instead of n log and n additions.

Just an idea...

**Comment by fcomida** [comment]
I'll try that, thank you. drago is fast enough, I'm focusing on mantiuk06
now. Davide did some work with sse2 for mantiuk06 some time ago, maybe it
can be improved.

**Comment by heckflosse** [comment]
Franco, my log stuff it's not worth to try :( It's not numerically stable and to get it stable it's slower than before.

**Comment by heckflosse** [comment]
The first part of `denormalizeLuminance` in mantiuk06 (contrast_domain.cpp) looks very similar to findmaxminpercentile ;-)

**Comment by heckflosse** [comment]
Maybe worth a try to use pow_F
`#define pow_F(a,b) (xexpf(b*xlogf(a)))`
insteaf of pow() in case you already use the sleef functions...

**Comment by fcomida** [comment]
Got it! Hehe

**Comment by heckflosse** [comment]
@fcomida

Hi Franco,

I'm curious about the speedups LuminanceHDR will get with the next release. I can't contribute active to coding but I can and will help with hints for speedups. Don't hesitate to ask me in case you detected a bottleneck in code (or even if you think the code is slow without having detected the bottleneck)

Ingo

**Comment by fcomida** [comment]
Sure, I appreciate it. My actal goal is to release 2.5.2 as soon as
possible since a couple of annoying bugs has been fixed. Then I will focus
on a new antighosting engine, better raw support and trying speeding up
tonemapping operators.
Do you think it would be possible using RT as an optional raw developer for
LHDR? Maybe this would only  make sense for creating an HDR from a single
raw, not for merging multiple exposures. Just thinking out loud...

**Comment by heckflosse** [comment]
@fcomida

> Do you think it would be possible using RT as an optional raw developer for
LHDR?

What do you mean by `raw developer`?

Do you mean for decoding raw files or also for preprocessing and demosaic?

Or even more?

**Comment by fcomida** [comment]
The problem is that more, for merging different exposures we need demosaic,
sometimes denoising, color correction, chromatic aberrations corrections,
maybe lens distorsion correction...with RT we'll have something more
interactive.

**Comment by fcomida** [comment]
Right now raw development options are in preferences an they are global, so
to speak. I was already thinking about developing a gui for optionally
changing them on the fly with maybe some kind of preview...

**Comment by jgoffredo** [comment]
Sometimes I use UFRaw to preprocess before merging.

I make lens correction, white balance correction, denoising etc. I write 16 bits TIFFs, and call Luminace HDR to merge, tone map etc.

Sometimes I tone map using Cinepaint, making curves by hand.

**Comment by fcomida** [comment]
Hi João,

do you launch UFRaw for each exposure and then write output on file? I
remember a plugin for using UFRaw from inside Gimp, the problem is that raw
developers handle an image at once.

**Comment by jgoffredo** [comment]
I launch UFRaw with all files in command line, but the first one is my reference. For example:

ufraw 3.nef 1.nef 2.nef 4.nef 5.nef

The reference in this example is the 3rd file. I use it for white balance, lens correction and other things. Is the only I really edit. The others (1.nef, 2.nef, 4.nef and 5.nef in this example) only copy the edit. I only save then using same edit parameters.

You don't need gimp to use ufraw, and can call from command line.

**Comment by heckflosse** [comment]
Hi Franco,

I agree that the raw processing in lhdr is not on par with rt. The demosaic code in rt (Amaze, lmmse, igv) is much faster than the libraw code for example. Same for raw ca-correction (not to speak of raw auto ca-correction...) 

But, using the rt raw engine in its current state is also not so easy. I would suggest to try using state of the art demosaic and ca-correction code from rt in first step. For example amaze demosaic of a 36 MP raw on my machine takes less than 0.5 seconds. I guess that would be a big improvement for lhdr while loading (and demosaicing) raw files

**Comment by fcomida** [comment]
I know ufraw can be used in batch mode from cli, I was thinking to
something that can be used from lhdr gui directly, for whatever reason the
wonderful 'tool box' philosophy of unix tradition doesn't integrate well
with the gui paradigm and most of our users are on windows.
Ingo I'll take a look at rt demosicing code.

**Comment by heckflosse** [comment]
@fcomida
In rt the following demosaicers are optimized for speed:

for Bayer Sensors:
Amaze
LMMSE
IGV
VNG4
DCB

for xtrans sensors:
3-pass
1-pass

**Comment by heckflosse** [comment]
@fcomida Franco, about drago

> Added openmp: 7.5x faster :D

> drago is fast enough

I played a bit with drago and got this results in my prototype. Measured in `pfstmo_drago03(...)` using a 24 MPixel file:

```
drago in current master branch: 11.8 seconds
drago in my prototype         :  0.3 seconds
```
If your are interested I can create a pr for review at the weekend.

Ingo

**Comment by fcomida** [comment]
Sure, go ahead. Is it sse2 only or avx?

**Comment by heckflosse** [comment]
sse2 + openmp + some other optimizations

**Comment by heckflosse** [comment]
I created #80
