### ISSUE TITLE
Automatically append the file extension for saving

### ISSUE THREAD

**Issue by sguyader** [LuminanceHDR/LuminanceHDR#82]
Currently, when I want to save a file (HDR or LDR), if I don't append the extension myself (.jpg, .tif, ...) the program fails to save with this simple message "Failed to save...." without giving a clue about why it failed.

LHDR will save successfully only if I append the file extension manually, which is a pain for repetitive tasks.

**Comment by fcomida** [comment]
HDRs are saved with the extension selected in "filter" dropbox but the extension isn't shown in the saving dialog (I'll fix this). LDRs are saved as jpeg by default and the extension is appended to the filename in saving dialog. Are you on Windows? I have to check this, I remember I fixed a bug on Windows not adding file name extension....anyway it'll be ok for 2.5.2. Thanks for reportinig it.

**Comment by sguyader** [comment]
Hi, no I'm on Linux and the extension is not appended by default for HDRs nor LDRs. If I don't appended the extension manually, saving fails.

**Comment by fcomida** [comment]
@sguyader It should be ok now in master.

**Comment by sguyader** [comment]
Thanks!
