### ISSUE TITLE
Default file location on save

### ISSUE THREAD

**Issue by jgt1942** [LuminanceHDR/LuminanceHDR#9]
I'd like to see an option that would auto save the HDR file in the folder of the source file.

**Comment by lapo-luchini** [comment]
Also, using the name of the (first?) source file.

Usually when I merge (IMG_0001.jpg, IMG_0002.jpg, IMG_0003.jpg) I create IMG_0001-0003.exr (in the same folder), but anything is better than the current (fixed name) in (fixed directory).

**Comment by fcomida** [comment]
@lapo-luchini @jgt1942 save files as first-last_suffix.extension where first
    == 1st bracketed image name, last == last bracketed image, suffix is
    either tonemapping parameters or HDR creation model.
see commit 3b6d960761cd38b5c4e1ba37f225eb67590b0474

Im closing this.
