### ISSUE TITLE
When saving, pre-filled filename textbox is cleared when clicking on Places

### ISSUE THREAD

**Issue by Beep6581** [LuminanceHDR/LuminanceHDR#90]
v2.0.2-12-g 064bded
When I hit ctrl+s the "name" field is pre-filled, but when I click on one of the "places" shortcuts on the left side of the "Save the HDR image as..." window the "name" field is cleared.

**Comment by fcomida** [comment]
@Beep6581 I cannot reproduce it, I actually cannot reproduce any of your latest bug reports.

**Comment by Beep6581** [comment]
Using Qt 5.9.3 and GCC 5.4.0.
```
cmake \
    -DCMAKE_CXX_FLAGS="-std=c++11 -Wno-deprecated-declarations -Wno-unused-result" \
    -DCMAKE_C_FLAGS="-O3 -pipe" \
(...)
```

**Comment by fcomida** [comment]
@Beep6581 I think this one is now fixed in master. Can you confirm?

**Comment by Beep6581** [comment]
Confirmed, no longer reproducible in `v.2.5.1-351-g`8b83caeb using Qt 5.11.3.
