### ISSUE TITLE
Add preview in HDR creation wizard

### ISSUE THREAD

**Issue by bruceg** [LuminanceHDR/LuminanceHDR#95]
When creating an HDR wizard, the final step offers many choices, but no visual indication of how they will change the resulting image. Also, the most time consuming parts of the process happen before this step, particularly alignment and anti-ghosting. Repeating the last step to try different model, weighting, and curve settings takes an excessive amount of time.

It would be useful to have some kind of visual preview function in this step, as there is in the others. To make it responsive, it should work on reduced size image data (possibly as little as a few hundred pixels on a side). Visually, I think it should work like the preview in the first step after the images are loaded, where each change to the settings is immediately reflected in the preview. A histogram graph like in the main window would also be important, to see how the parameters affect the final range of values.

**Comment by fcomida** [comment]
@bruceg Hi Bruce, working on it, almost done. I opted for a full size preview
![screenshot_20180606_124301](https://user-images.githubusercontent.com/11018726/41036551-acd96cc4-6990-11e8-9c27-b66566c9db61.png)
![screenshot_20180606_130144](https://user-images.githubusercontent.com/11018726/41036552-ad051cb6-6990-11e8-90d5-20a06ee1f668.png)
![screenshot_20180606_135047](https://user-images.githubusercontent.com/11018726/41036553-ad2d537a-6990-11e8-9525-6739a25030be.png)
